// Typed access to the baked GitHub contribution snapshot used by the landing
// hero. The snapshot is generated by `scripts/build-contributions.mjs` and
// crucially includes PRIVATE contribution counts (owner token) — so the
// skyline reflects all the invisible work, not just public repos.
import data from "@/data/contributions.json";

export type ContributionDay = {
  /** ISO date, YYYY-MM-DD */
  d: string;
  /** contribution count that day (incl. private) */
  c: number;
  /** weekday, 0=Sun..6=Sat (keeps grid rows calendar-aligned) */
  w: number;
};

export type ContributionData = {
  login: string;
  generatedAt: string;
  range: { from: string; to: string };
  /** total contributions in range (public + private) */
  total: number;
  /** how many of `total` are private/restricted */
  private: number;
  /** busiest single day */
  maxCount: number;
  /** days with ≥1 contribution */
  activeDays: number;
  /** total days in range */
  totalDays: number;
  /** columns of 7 days each (GitHub calendar layout) */
  weeks: ContributionDay[][];
};

export const contributions = data as ContributionData;
