/**
 * 자율주행 용어 사전.
 *
 * 본문에 등장하는 전문용어를 클릭하면 뜨는 모달의 원본 데이터다.
 * 이 파일은 서버(remark 플러그인)와 클라이언트(모달) 양쪽에서 쓰므로
 * "server-only" 를 붙이지 않는다. 다만 모달은 dynamic import 로만 불러
 * 이 데이터가 첫 화면 번들에 실리지 않게 한다.
 *
 * body 규칙 — 각 원소가 한 문단. "- " 로 시작하면 불릿.
 * 인라인은 **굵게** 와 `코드` 두 가지만 지원한다(모달 렌더러가 해석).
 */

export type GlossaryCategory =
  | "센서·좌표"
  | "씬·데이터"
  | "카메라·영상"
  | "어노테이션"
  | "인지 태스크"
  | "예측·계획·제어"
  | "로그·포맷"
  | "데이터 인프라"
  | "도구"
  | "모델·학습";

export interface GlossaryEntry {
  /** URL/앵커로도 쓰이는 안정적 키 */
  id: string;
  /** 모달 제목 */
  term: string;
  /** 풀네임 (영문 확장) */
  full?: string;
  category: GlossaryCategory;
  /** 한 줄 정의 */
  summary: string;
  /** 본문 문단 */
  body: string[];
  /** 함께 볼 용어 id */
  related?: string[];
  /** 더 읽을 글 */
  post?: { label: string; href: string };
  /**
   * 본문에서 자동으로 잡을 표기들. 생략하면 [term] 만 잡는다.
   * 대소문자를 그대로 구분하므로 변형이 필요하면 전부 적는다.
   */
  match?: string[];
  /** 자동 매칭에서 제외 (명시적 <Term id> 로만 노출) */
  manualOnly?: boolean;
}

export const GLOSSARY: GlossaryEntry[] = [
  /* ─────────────────────────── 로그·포맷 ─────────────────────────── */
  {
    id: "mcap",
    term: "MCAP",
    full: "Message Capture and log container format",
    category: "로그·포맷",
    summary:
      "종류가 다른 메시지를 한 파일에 시간순으로 담고, 인덱스로 임의 시점에 바로 점프할 수 있는 자기설명형 로그 컨테이너.",
    body: [
      "자율주행 로그는 20Hz 라이다, 30Hz 카메라 여러 대, 100Hz IMU, CAN, 그리고 인지·계획·제어의 출력까지 **서로 다른 주기의 이종 메시지**가 한 시간축에 섞인 스트림이다. MCAP은 이걸 담기 위한 컨테이너다.",
      "- **스키마 불가지(schema-agnostic)** — ROS 메시지든 Protobuf든 JSON Schema든, 채널마다 스키마를 파일 안에 함께 박는다. 파일 하나만 있으면 무엇이 들었는지 알 수 있다(self-describing).",
      "- **인덱싱** — 파일 끝의 요약(summary) 구역에 청크 인덱스가 있어 \"37.5초의 전방 라이다\"로 곧장 seek 한다. 페타바이트 리플레이의 전제.",
      "- **ROS 비의존** — 프로파일만 `ros2` 로 잡으면 ROS 도구와 붙고, 비워두면 순수 Protobuf 스택으로도 쓴다.",
      "Foxglove가 만들어 사실상 표준이 됐고, rosbag2의 기본 저장 플러그인으로도 채택됐다.",
    ],
    related: ["rosbag", "chunk", "channel", "schema-record", "attachment", "log-time", "foxglove", "parquet"],
    post: { label: "MCAP 완전 정복", href: "/posts/av-mcap" },
    match: ["MCAP", "mcap"],
  },
  {
    id: "rosbag",
    term: "rosbag",
    category: "로그·포맷",
    summary: "ROS 생태계의 고전적 로그 컨테이너. 토픽별 메시지를 시간순으로 담는다.",
    body: [
      "ROS 1의 `.bag`, ROS 2의 `rosbag2`(기본 저장소가 sqlite3였다가 MCAP으로 이동)로 이어진다. 생태계는 두텁지만 약점이 분명하다.",
      "- 스키마가 **ROS 메시지 정의에 묶인다**. 그 정의가 없는 환경에서는 파일을 해석할 수 없다.",
      "- 대용량에서 **탐색(seek)과 인덱싱이 약하다**. 한가운데 3초를 보려고 앞부분을 다 훑는 일이 생긴다.",
      "- ROS 밖 도구(학습 파이프라인, 클라우드 분석)와 붙이기 번거롭다.",
      "그래서 기록 계층이 MCAP으로 이동 중이다. `mcap convert in.bag out.mcap` 으로 변환할 수 있다.",
    ],
    related: ["mcap", "ros2"],
    match: ["rosbag", "ROS bag"],
  },
  {
    id: "ros2",
    term: "ROS 2",
    full: "Robot Operating System 2",
    category: "로그·포맷",
    summary: "로봇 소프트웨어의 사실상 표준 미들웨어. 토픽 기반 발행/구독으로 노드들이 통신한다.",
    body: [
      "'운영체제'라는 이름과 달리 실제로는 **메시지 미들웨어 + 빌드 시스템 + 도구 모음**이다. 노드가 토픽에 발행하고 다른 노드가 구독한다.",
      "ROS 2는 DDS 위에서 돌고, 메시지는 **CDR**로 직렬화된다. MCAP에 담을 때 `message_encoding` 이 `cdr`, `schema_encoding` 이 `ros2msg` 가 되는 이유다.",
      "양산 자율주행 스택이 ROS 2를 그대로 쓰는 경우는 드물지만(실시간성·안전 인증), **로그 포맷과 도구 생태계**는 ROS 규약을 따라가는 경우가 많다.",
    ],
    related: ["mcap", "cdr", "topic", "tf"],
    match: ["ROS 2", "ROS2"],
  },
  {
    id: "topic",
    term: "토픽",
    full: "topic",
    category: "로그·포맷",
    summary: "같은 성격의 메시지가 흐르는 이름 붙은 통로. `/sensor/lidar/top/points` 처럼 경로 형태로 짓는다.",
    body: [
      "MCAP 안에서 토픽은 **채널(Channel)** 로 표현되고, 채널은 스키마 하나를 가리킨다. 즉 `토픽 1개 = 채널 1개 = 스키마 1개`가 기본이다.",
      "토픽 이름 규약은 로그를 회사 자산으로 만드느냐 쓰레기로 만드느냐를 가른다. 실무에서 자주 쓰는 뼈대:",
      "- `/sensor/<종류>/<위치>/<신호>` — 원본 센서",
      "- `/perception/<태스크>` — 인지 출력(objects, occupancy, lanes, traffic_lights)",
      "- `/prediction/*`, `/planning/*`, `/control/*` — 하류 단계",
      "- `/tf`, `/tf_static` — 좌표 변환 트리",
      "이름을 나중에 바꾸면 과거 로그 전부가 질의에서 빠진다. **네이밍은 스키마만큼 중요한 계약**이다.",
    ],
    related: ["channel", "mcap", "schema-record"],
    match: ["토픽"],
  },
  {
    id: "channel",
    term: "채널",
    full: "Channel record",
    category: "로그·포맷",
    summary: "MCAP 안에서 토픽 하나를 나타내는 레코드. 스키마 id, 메시지 인코딩, 토픽 이름을 들고 있다.",
    body: [
      "채널 레코드는 `id`, `schema_id`, `topic`, `message_encoding`, `metadata` 로 이뤄진다. 메시지 레코드는 자기 페이로드와 `channel_id` 만 들고 있어서, **어떤 스키마로 풀어야 하는지는 채널을 거쳐 알아낸다.**",
      "`message_encoding` 은 페이로드를 어떤 규칙으로 직렬화했는지다 — `cdr`(ROS 2), `ros1`, `protobuf`, `json`, `flatbuffer`.",
      "채널 `metadata` 는 자유로운 키-값 맵이다. 센서 시리얼 번호, 캘리브레이션 버전 같은 걸 여기 박아두면 나중에 로그만 보고 추적할 수 있다.",
    ],
    related: ["schema-record", "topic", "mcap"],
    match: ["채널(Channel)", "Channel 레코드"],
    manualOnly: true,
  },
  {
    id: "schema-record",
    term: "스키마 레코드",
    full: "Schema record",
    category: "로그·포맷",
    summary: "메시지 페이로드를 해석하는 방법을 파일 안에 박아둔 레코드. MCAP이 self-describing인 이유.",
    body: [
      "`id`, `name`, `encoding`, `data` 로 이뤄지고, `data` 에 스키마 정의 자체가 바이트로 들어간다.",
      "- `ros2msg` / `ros1msg` — `.msg` 텍스트 정의",
      "- `protobuf` — 컴파일된 `FileDescriptorSet` 바이트",
      "- `jsonschema` — JSON Schema 문서",
      "이 덕분에 3년 전 로그를 지금 열어도 필드 이름과 타입을 알 수 있다. **스키마를 외부 저장소에만 두면 이 성질이 깨진다** — 그 저장소가 사라지면 로그도 같이 죽는다.",
      "스키마 진화(필드 추가/삭제)를 견디는 정도는 인코딩마다 다르다. Protobuf가 가장 관대하고, ROS msg는 정의가 바뀌면 과거 로그와 어긋나기 쉽다.",
    ],
    related: ["channel", "protobuf", "cdr", "mcap"],
    match: ["스키마 레코드"],
  },
  {
    id: "protobuf",
    term: "Protobuf",
    full: "Protocol Buffers",
    category: "로그·포맷",
    summary: "구글이 만든 이진 직렬화 포맷. 필드마다 번호를 붙여 스키마가 변해도 과거 데이터를 읽을 수 있다.",
    body: [
      "`.proto` 로 메시지를 정의하고 언어별 코드를 생성한다. 자율주행 로그에서 중요한 건 **전방/후방 호환성**이다.",
      "- 필드에 번호가 붙어 있어 **새 필드를 추가해도 옛 리더가 무시하고 지나간다.**",
      "- 삭제한 번호를 `reserved` 로 막으면 재사용 사고를 막는다.",
      "몇 년치 로그가 쌓이는 곳에서는 이 성질이 결정적이다. ROS msg 기반 스택이 MCAP 전환 시 Protobuf를 함께 검토하는 이유가 여기 있다.",
      "MCAP에 담으면 `schema_encoding=protobuf`(FileDescriptorSet), `message_encoding=protobuf` 가 된다.",
    ],
    related: ["schema-record", "cdr", "mcap"],
    match: ["Protobuf", "protobuf", "프로토버프"],
  },
  {
    id: "cdr",
    term: "CDR",
    full: "Common Data Representation",
    category: "로그·포맷",
    summary: "DDS/ROS 2가 쓰는 이진 직렬화 규칙. 필드가 순서대로 붙어 있고 필드 번호가 없다.",
    body: [
      "구조가 단순해 빠르지만, **필드 번호가 없어서 스키마가 바뀌면 그 자리에서 어긋난다.** 메시지 정의에 필드 하나를 끼워 넣는 순간 과거 로그와 새 로그가 서로 다른 해석을 요구하게 된다.",
      "그래서 ROS 2 + CDR로 로그를 쌓는 조직은 **메시지 정의에 버전을 박고**, 정의가 바뀌면 토픽 이름을 바꾸거나 스키마 이름에 버전을 붙이는 규약을 둔다.",
    ],
    related: ["protobuf", "ros2", "schema-record"],
    match: ["CDR"],
  },
  {
    id: "chunk",
    term: "청크",
    full: "Chunk record",
    category: "로그·포맷",
    summary: "여러 메시지를 묶어 한 덩어리로 압축한 단위. MCAP의 압축과 seek는 모두 이 단위로 일어난다.",
    body: [
      "청크에는 `message_start_time`, `message_end_time`, 압축 방식(`zstd`/`lz4`/없음), 그리고 압축된 메시지들이 들어간다. 파일 요약부의 **청크 인덱스**가 각 청크의 시간 범위와 바이트 오프셋을 들고 있어서, 리더는 필요한 청크만 골라 읽는다.",
      "청크 크기는 트레이드오프다.",
      "- **크게** — 압축률이 좋아지고 메타 오버헤드가 줄지만, 1초를 보려고 큰 덩어리를 통째로 풀어야 한다.",
      "- **작게** — seek가 정밀해지지만 파일이 커지고 인덱스가 불어난다.",
      "고빈도 대용량 토픽(라이다·이미지)과 저빈도 토픽(계획 출력)을 **다른 파일이나 다른 청크 정책**으로 나누는 게 실무의 흔한 최적화다.",
    ],
    related: ["mcap", "zstd", "summary-section"],
    match: ["청크"],
  },
  {
    id: "summary-section",
    term: "요약 구역",
    full: "Summary section",
    category: "로그·포맷",
    summary: "MCAP 파일 끝에 붙는 인덱스 구역. 전체를 훑지 않고 파일의 목차를 읽게 해준다.",
    body: [
      "요약 구역에는 스키마·채널 목록의 사본, **청크 인덱스**, 첨부/메타데이터 인덱스, 그리고 **Statistics**(메시지 수, 채널별 개수, 시작/끝 시각)가 들어간다.",
      "그래서 `mcap info file.mcap` 은 수십 GB 파일이어도 즉시 답한다 — 꼬리만 읽기 때문이다.",
      "기록 중 프로세스가 죽으면 이 구역이 안 쓰인 채 파일이 끝난다. 그런 파일은 **인덱스 없는 로그**가 되어 seek가 안 된다. `mcap recover` 로 데이터 구역을 훑어 되살린다.",
    ],
    related: ["chunk", "mcap", "mcap-cli", "statistics"],
    match: ["요약 구역", "Summary section"],
  },
  {
    id: "statistics",
    term: "Statistics 레코드",
    category: "로그·포맷",
    summary: "메시지 총수, 채널별 개수, 시작/끝 시각을 담은 요약 레코드. 변환 검증의 기준이 된다.",
    body: [
      "포맷 마이그레이션에서 \"빠짐없이 옮겼는가\"를 증명하는 가장 싼 방법이 이것이다. 원본에서 센 채널별 메시지 수와 변환 결과의 `channel_message_counts` 를 대조하면 된다.",
      "시작/끝 시각(`message_start_time`, `message_end_time`)은 로그 카탈로그를 만들 때 그대로 컬럼으로 쓴다.",
    ],
    related: ["summary-section", "mcap-cli", "mcap"],
    match: ["Statistics"],
  },
  {
    id: "attachment",
    term: "첨부",
    full: "Attachment record",
    category: "로그·포맷",
    summary: "로그 안에 임의의 파일을 통째로 넣는 자리. 캘리브레이션 YAML, 지도 조각, 모델 가중치를 담는다.",
    body: [
      "`name`, `media_type`, `log_time`, `create_time`, 그리고 바이트 덩어리로 이뤄진다. 요약부에 첨부 인덱스가 있어 **파일 전체를 훑지 않고 꺼낼 수 있다.**",
      "가장 값어치 있는 용도는 **캘리브레이션 동봉**이다. 로그를 3년 뒤에 열어도 그때 쓰던 내외부 파라미터가 파일 안에 같이 있으면, 좌표 변환을 재현할 수 있다. 외부 DB만 믿으면 DB 스키마가 바뀌는 순간 과거 로그가 해석 불능이 된다.",
      "반대로 **자주 바뀌는 것은 첨부에 넣지 마라.** 어노테이션은 여러 번 갱신되므로 로그 밖 사이드카에 두는 편이 낫다.",
    ],
    related: ["metadata-record", "calibration", "annotation", "mcap"],
    match: ["첨부(attachment)", "Attachment"],
  },
  {
    id: "metadata-record",
    term: "Metadata 레코드",
    category: "로그·포맷",
    summary: "로그에 붙이는 키-값 맵. 차량 id, 소프트웨어 커밋, ODD 태그 같은 맥락을 적는다.",
    body: [
      "`name` 과 `map<string,string>` 한 벌이다. 첨부와 마찬가지로 요약부에 인덱스가 있다.",
      "여기에 무엇을 적어두느냐가 나중에 **로그를 질의할 수 있는가**를 결정한다. 실무에서 거의 항상 넣는 것들:",
      "- `vehicle_id`, `run_id`, `driver_mode`(수동/자율)",
      "- 스택 버전 — git sha, 모델 버전, 캘리브레이션 버전",
      "- ODD 태그 — 날씨, 시간대, 도로 유형",
      "이걸 안 적으면 나중에 페타바이트를 다시 훑어 추론해야 한다.",
    ],
    related: ["attachment", "odd", "curation", "mcap"],
    match: ["Metadata 레코드"],
  },
  {
    id: "log-time",
    term: "log_time / publish_time",
    category: "로그·포맷",
    summary: "MCAP 메시지가 들고 있는 두 개의 시각. 둘 다 '기록 시스템의 시계'이지 센서가 세상을 본 시각이 아니다.",
    body: [
      "- `log_time` — 기록기가 이 메시지를 파일에 적은 시각. **인덱스와 seek가 기준으로 삼는 값.**",
      "- `publish_time` — 발행자가 내보낸 시각. 전송 지연을 재는 데 쓴다.",
      "여기에 세 번째 시계가 있다. 메시지 페이로드 안의 **센서 캡처 시각**(예: ROS `header.stamp`, 라이다의 점별 타임스탬프)이다.",
      "**센서 융합과 좌표 변환은 반드시 캡처 시각을 써야 한다.** log_time으로 라이다와 카메라를 맞추면 큐 지연만큼 어긋나고, 60km/h에서 10ms는 17cm다. 실무 사고의 상당수가 여기서 난다.",
      "반대로 \"이 로그의 37.5초 지점\" 같은 탐색은 log_time 기준이다. 두 시계를 섞지 않는 규약을 문서로 못 박아야 한다.",
    ],
    related: ["time-sync", "sensor-fusion", "ptp", "mcap"],
    match: ["log_time", "publish_time", "기록 시각"],
  },
  {
    id: "zstd",
    term: "zstd",
    full: "Zstandard",
    category: "로그·포맷",
    summary: "압축률과 속도의 균형이 좋은 압축 알고리즘. MCAP 청크 압축의 기본 선택지.",
    body: [
      "MCAP은 청크 단위로 `zstd` 또는 `lz4` 압축을 지원한다. 대략의 감각으로,",
      "- **zstd** — 압축률이 높다. 저장 비용과 네트워크 전송이 중요한 아카이브에 맞는다.",
      "- **lz4** — 압축/해제가 훨씬 빠르다. 차량에서 실시간 기록하거나, 학습 때 반복해 읽는 데이터에 맞는다.",
      "이미지·비디오처럼 **이미 압축된 페이로드**에는 이중 압축의 이득이 거의 없다. 그런 토픽은 압축을 끄는 게 낫다.",
    ],
    related: ["chunk", "mcap", "compressed-image"],
    match: ["zstd", "lz4"],
  },
  {
    id: "mcap-cli",
    term: "mcap CLI",
    category: "도구",
    summary: "MCAP 파일을 들여다보고 고치는 공식 명령줄 도구.",
    body: [
      "- `mcap info` — 채널·스키마·메시지 수·시간 범위를 즉시 (요약부만 읽는다)",
      "- `mcap list channels|schemas|chunks` — 목록",
      "- `mcap cat --topics /perception/objects` — 메시지 덤프",
      "- `mcap filter in.mcap -o out.mcap -y '/sensor/.*' -S 100 -E 130` — 토픽·시간 구간 잘라내기",
      "- `mcap merge a.mcap b.mcap -o all.mcap` — 여러 로그 합치기",
      "- `mcap convert in.bag out.mcap` — rosbag 변환",
      "- `mcap doctor` — 인덱스·CRC 무결성 검사. **CI에 넣어야 하는 명령.**",
      "- `mcap recover` — 기록 중 죽어 인덱스가 없는 파일 되살리기",
      "- `mcap add attachment|metadata`, `mcap get attachment` — 첨부·메타 관리",
    ],
    related: ["mcap", "summary-section", "attachment"],
    match: ["mcap CLI", "`mcap` CLI"],
  },
  {
    id: "parquet",
    term: "Parquet",
    full: "Apache Parquet",
    category: "데이터 인프라",
    summary: "컬럼 지향 저장 포맷. 필요한 열만 읽고 조건으로 걸러내는 분석 질의에 최적화돼 있다.",
    body: [
      "행 단위 로그(MCAP)와 정반대의 목적을 가진다. 로그는 \"이 시점의 모든 것\"을 읽지만, 분석은 \"모든 시점의 이 열 하나\"를 읽는다.",
      "- **열 프루닝** — 200개 컬럼 중 3개만 읽는다.",
      "- **술어 푸시다운** — 통계(min/max)를 보고 조건에 안 맞는 덩어리를 통째로 건너뛴다.",
      "- **압축 효율** — 같은 타입이 붙어 있어 훨씬 잘 눌린다.",
      "그래서 실무는 2층으로 간다. **기록·재생은 MCAP, 분석·학습 큐레이션은 Parquet.** 원본 점군은 그대로 두고 파생 신호와 메타만 컬럼으로 굽는다.",
    ],
    related: ["mcap", "delta-lake", "lakehouse", "curation", "databricks"],
    post: { label: "로그 데이터와 포맷", href: "/posts/av-data-formats" },
    match: ["Parquet", "parquet", "컬럼형"],
  },

  /* ─────────────────────────── 데이터 인프라 ─────────────────────────── */
  {
    id: "lakehouse",
    term: "레이크하우스",
    full: "Lakehouse",
    category: "데이터 인프라",
    summary:
      "값싼 오브젝트 스토리지 위에 테이블 형식과 트랜잭션을 얹어, 데이터 레이크에서 웨어하우스처럼 질의하게 만든 구조.",
    body: [
      "과거엔 두 시스템을 따로 뒀다. 원본을 쌓는 **데이터 레이크**(싸지만 스키마도 트랜잭션도 없음)와 정제본을 담는 **데이터 웨어하우스**(빠르지만 비싸고 원본을 못 담음). 복사가 계속 생기고 둘이 어긋났다.",
      "레이크하우스는 레이크의 파일(Parquet) 위에 **테이블 메타데이터 계층**(Delta Lake·Iceberg·Hudi)을 얹어 ACID 트랜잭션, 스키마 강제, 타임 트래블을 준다.",
      "자율주행에 잘 맞는 이유는 규모다. 페타바이트 원본을 옮기지 않고 그 자리에서 질의할 수 있다.",
    ],
    related: ["parquet", "delta-lake", "databricks", "vast", "curation"],
    match: ["레이크하우스", "Lakehouse"],
  },
  {
    id: "delta-lake",
    term: "Delta Lake",
    category: "데이터 인프라",
    summary: "Parquet 파일 위에 트랜잭션 로그를 얹어 ACID와 버전 관리를 주는 테이블 포맷.",
    body: [
      "`_delta_log/` 에 JSON 커밋 로그를 쌓아 \"지금 이 테이블은 어떤 파일들로 이뤄져 있는가\"를 원자적으로 기록한다.",
      "- **ACID** — 쓰는 중에 읽어도 반쪽 상태가 보이지 않는다. 수십 개 잡이 동시에 굽는 환경에서 필수.",
      "- **타임 트래블** — 과거 버전을 그대로 읽는다. **어떤 데이터가 어떤 모델을 만들었는지** 못 박는 가장 실용적인 수단.",
      "- **스키마 진화** — 컬럼 추가를 안전하게 반영한다.",
      "경쟁 포맷으로 Apache Iceberg가 있고, 최근에는 서로 읽을 수 있게 수렴하는 중이다.",
    ],
    related: ["parquet", "lakehouse", "databricks", "data-versioning"],
    match: ["Delta Lake", "Delta 테이블"],
  },
  {
    id: "databricks",
    term: "Databricks",
    category: "데이터 인프라",
    summary:
      "Spark를 만든 팀이 세운 레이크하우스 플랫폼. 대규모 배치 변환, SQL 질의, 거버넌스, ML 실험 추적을 한 곳에 묶는다.",
    body: [
      "자율주행 스택에서 맡는 자리는 대체로 **MCAP 다음 층**이다.",
      "- **대규모 변환** — 수만 개 MCAP을 병렬로 열어 파생 신호(속도·기동·객체 수·날씨 태그)를 뽑아 Delta 테이블로 굽는다.",
      "- **씬 큐레이션** — 구워진 테이블 위에서 \"야간 + 우천 + 좌회전 + 보행자\"를 SQL로 뽑아 학습 세트를 만든다.",
      "- **거버넌스(Unity Catalog)** — 누가 어떤 주행 데이터에 접근했는지, 어떤 테이블이 어디서 파생됐는지(리니지)를 추적한다. 얼굴·번호판이 찍힌 영상이 섞이는 도메인이라 중요도가 높다.",
      "- **MLflow** — 데이터 스냅샷 버전과 모델 실험을 묶어 재현성을 만든다.",
      "주의할 점은 **원본 센서 데이터를 플랫폼 안으로 다 밀어 넣으려 하지 않는 것**이다. 점군·영상 원본은 스토리지에 두고, 플랫폼은 메타·파생 신호와 포인터를 다룬다.",
    ],
    related: ["lakehouse", "delta-lake", "spark", "vast", "curation", "parquet"],
    post: { label: "AV 데이터 플랫폼", href: "/posts/av-data-platform" },
    match: ["Databricks", "데이터브릭스"],
  },
  {
    id: "spark",
    term: "Spark",
    full: "Apache Spark",
    category: "데이터 인프라",
    summary: "분산 데이터 처리 엔진. 수천 개 파일을 클러스터에 흩뿌려 병렬로 변환한다.",
    body: [
      "자율주행에서 Spark가 가장 잘 하는 일은 **MCAP 팬아웃**이다. 로그 파일 목록을 파티션으로 나눠 각 익스큐터가 자기 몫의 파일을 열고 메시지를 훑어 요약 행을 뱉는다.",
      "주의점: 하나의 MCAP은 순차 스트림이라 파일 **안**을 쪼개 병렬화하기 어렵다. 병렬성의 단위를 **파일**로 잡아야 한다. 그래서 로그 분할 정책(파일당 몇 초·몇 GB)이 곧 처리 성능이 된다.",
    ],
    related: ["databricks", "mcap", "parquet"],
    match: ["Spark"],
  },
  {
    id: "vast",
    term: "VAST Data",
    category: "데이터 인프라",
    summary:
      "올플래시 분산 스토리지 플랫폼. NFS·S3를 한 네임스페이스로 제공해 대규모 학습에서 GPU가 굶지 않게 하는 계층.",
    body: [
      "자율주행 데이터가 스토리지에 거는 부하는 두 종류가 겹쳐 있어 고약하다.",
      "- **거대한 순차 파일** — 수십 GB짜리 로그를 리플레이·변환하며 순차로 훑는다.",
      "- **수십억 개 작은 객체** — 학습 배치가 이미지·점군 조각을 무작위 순서로 집는다.",
      "전통적인 HDD 기반 레이크는 두 번째에서 무너진다. 무작위 읽기가 디스크 탐색으로 죽고 GPU가 데이터 대기로 논다. 올플래시 공유 스토리지는 **모든 노드가 모든 데이터를 균일한 지연으로 읽는** 구조로 이 문제를 겨냥한다.",
      "실무에서 나오는 값어치는 단순하다. **복사본이 줄어든다.** 기록·변환·학습·시각화가 같은 네임스페이스(NFS로도 S3로도 보이는)를 보면, 단계마다 페타바이트를 옮겨 붙이는 일이 사라진다.",
      "다만 비싸다. 그래서 실무 설계는 **계층화**다 — 최근·학습 중인 데이터는 플래시, 오래된 원본은 저비용 오브젝트 스토리지나 아카이브로 내린다.",
    ],
    related: ["object-storage", "databricks", "lakehouse", "training-io"],
    post: { label: "AV 데이터 플랫폼", href: "/posts/av-data-platform" },
    match: ["VAST Data", "VAST"],
  },
  {
    id: "object-storage",
    term: "오브젝트 스토리지",
    full: "Object storage",
    category: "데이터 인프라",
    summary: "파일을 키-값 객체로 다루는 저비용 대용량 저장소(S3 등). 자율주행 원본 아카이브의 바닥.",
    body: [
      "싸고 사실상 무한히 늘어나지만 성질이 파일시스템과 다르다.",
      "- **요청당 지연이 크다.** 작은 파일 수백만 개를 하나씩 가져오면 학습이 I/O에 묶인다. → 샤드로 묶는다.",
      "- **리스팅이 느리다.** 디렉터리 개념이 없어 접두사 스캔이 비싸다. → 파일 목록 자체를 **카탈로그 테이블**로 관리한다.",
      "- **부분 읽기는 된다.** Range 요청을 지원하므로, 인덱스를 아는 로그는 필요한 청크만 당겨올 수 있다. 이것이 MCAP 인덱스의 클라우드 시대 값어치다.",
    ],
    related: ["vast", "parquet", "mcap", "training-io"],
    match: ["오브젝트 스토리지"],
  },
  {
    id: "training-io",
    term: "학습 I/O",
    category: "데이터 인프라",
    summary: "GPU가 계산하는 동안 다음 배치를 제때 공급하는 문제. 대규모 AV 학습의 실질적 병목.",
    body: [
      "멀티모달 AV 모델 한 스텝은 카메라 6~12장 + 점군 + 라벨을 요구한다. 배치 크기를 곱하면 초당 수 GB가 필요하다.",
      "해법은 대체로 이 순서다.",
      "- **샤딩** — 작은 파일을 순차 읽기 가능한 큰 샤드로 묶는다(WebDataset 등).",
      "- **전처리 굽기** — 매 스텝 원본을 디코딩하지 않고 미리 복셀·BEV 텐서로 구워 둔다.",
      "- **로컬 캐시** — 학습 노드의 NVMe에 에폭 단위로 미리 내린다.",
      "- **디코딩 오프로드** — JPEG·H.264 디코딩을 GPU로 넘긴다.",
      "\"GPU 사용률이 40%\"라는 증상은 대부분 모델이 아니라 여기서 온다.",
    ],
    related: ["object-storage", "vast", "compressed-image"],
    match: ["학습 I/O"],
  },
  {
    id: "data-versioning",
    term: "데이터 버저닝",
    category: "데이터 인프라",
    summary: "어떤 데이터 스냅샷이 어떤 모델을 학습시켰는지 못 박는 일. 성능 회귀의 원인을 찾는 전제.",
    body: [
      "코드만 버전 관리하고 데이터는 안 하면, 성능이 떨어졌을 때 원인이 모델인지 데이터인지 영영 못 가른다.",
      "수단은 여럿이다 — Delta Lake 타임 트래블, lakeFS(레이크에 git 같은 브랜치·커밋), DVC(파일 해시 + 원격 저장소).",
      "핵심은 도구가 아니라 **못 박는 대상**이다. `모델 v7 = 데이터 스냅샷 2026-07-01 + 라벨 스펙 v3 + 캘리브레이션 버전 x`. 셋 중 하나라도 빠지면 재현이 안 된다.",
    ],
    related: ["delta-lake", "annotation", "calibration", "curation"],
    match: ["데이터 버저닝", "lakeFS", "DVC"],
  },
  {
    id: "curation",
    term: "데이터 큐레이션",
    category: "데이터 인프라",
    summary: "페타바이트 로그에서 학습·평가에 쓸 장면을 골라내는 일. 라벨 예산이 유한하기 때문에 필요하다.",
    body: [
      "전부 라벨링할 수는 없다. 그래서 **무엇을 라벨링할지 고르는 일**이 성능을 좌우한다.",
      "- **실패 기반** — 모델이 틀린 장면, 사람이 개입(disengagement)한 장면.",
      "- **불확실성 기반** — confidence가 낮거나 앙상블이 갈리는 장면.",
      "- **희소성 기반** — 임베딩 공간에서 기존 데이터와 먼 장면.",
      "- **조건 기반** — ODD 조합으로 뽑기.",
      "이게 돌아가려면 로그가 **질의 가능**해야 한다. 큐레이션은 결국 로그 → 파생 컬럼 → SQL 로 이어지는 데이터 설계의 결과물이다.",
    ],
    related: ["long-tail", "parquet", "vqa", "data-flywheel", "odd"],
    match: ["큐레이션"],
  },
  {
    id: "data-flywheel",
    term: "데이터 플라이휠",
    category: "데이터 인프라",
    summary: "배포 → 실패 수집 → 유사 장면 발굴 → 라벨링 → 재학습 → 재배포로 도는 순환.",
    body: [
      "자율주행에서 성능을 만드는 건 한 번의 좋은 모델이 아니라 **이 바퀴가 도는 속도**다.",
      "바퀴가 멈추는 곳은 대개 정해져 있다 — 실패 장면을 못 찾거나(질의 불가), 유사 장면을 못 모으거나(임베딩 검색 없음), 라벨링이 몇 주 걸리거나, 데이터 버전을 못 박아 개선을 증명 못 하거나.",
      "데이터 엔지니어링의 목표는 모델을 만드는 게 아니라 **이 바퀴의 마찰을 줄이는 것**이다.",
    ],
    related: ["curation", "long-tail", "annotation", "data-versioning"],
    match: ["데이터 플라이휠", "플라이휠"],
  },
  {
    id: "long-tail",
    term: "롱테일",
    full: "Long tail",
    category: "데이터 인프라",
    summary: "드물지만 무한히 다양한 상황들. 자율주행 난이도의 대부분이 여기에 있다.",
    body: [
      "고속도로 직진은 데이터가 넘친다. 문제는 **도로에 떨어진 사다리, 역주행 오토바이, 눈에 덮인 차선, 수신호하는 경찰**처럼 각각은 드물지만 합치면 자주 일어나는 것들이다.",
      "롱테일은 데이터를 더 많이 모아서가 아니라 **골라서** 푼다. 무작위로 1만 시간을 더 모으면 고속도로 직진이 1만 시간 늘 뿐이다.",
    ],
    related: ["curation", "occ", "data-flywheel", "simulation"],
    match: ["롱테일"],
  },
  {
    id: "odd",
    term: "ODD",
    full: "Operational Design Domain",
    category: "예측·계획·제어",
    summary: "이 시스템이 작동한다고 보증하는 조건의 범위. 도로 유형·속도·날씨·시간대 등.",
    body: [
      "\"자율주행이 된다\"는 말은 항상 ODD를 전제로 한다. 고속도로 주간 맑음에서 되는 것과 골목 야간 폭우에서 되는 것은 완전히 다른 주장이다.",
      "데이터 관점에서 ODD는 **태그 스키마**다. 모든 로그에 날씨·조도·도로유형·속도대역을 붙여 두면 커버리지(어느 조건이 비었는가)를 측정할 수 있고, 평가 세트를 조건별로 쪼갤 수 있다.",
      "ODD 태그가 없는 로그 더미는 크기만 클 뿐 커버리지를 증명하지 못한다.",
    ],
    related: ["curation", "metadata-record", "simulation"],
    match: ["ODD"],
  },

  /* ─────────────────────────── 도구 ─────────────────────────── */
  {
    id: "foxglove",
    term: "Foxglove",
    category: "도구",
    summary: "로봇·자율주행 데이터 시각화 플랫폼. MCAP을 만든 곳이며, 로그를 열어 3D·이미지·플롯 패널로 본다.",
    body: [
      "데스크톱/웹 앱에서 MCAP·rosbag을 열거나, 실행 중인 차량에 WebSocket으로 붙어 실시간으로 본다.",
      "- **패널 조합** — 3D 뷰, 이미지, 플롯, 로그, 테이블을 레이아웃으로 저장해 팀이 공유한다.",
      "- **표준 스키마** — `foxglove.PointCloud`, `foxglove.CompressedImage`, `foxglove.FrameTransform`, `foxglove.SceneUpdate` 같은 well-known 스키마로 적으면 **패널이 알아서 그린다.** 커스텀 스키마면 변환기를 직접 붙여야 한다.",
      "- **좌표 프레임** — `frame_id` 와 변환 트리를 읽어 여러 센서를 한 3D 공간에 정합해 겹친다.",
      "MCAP 전환의 실질적 이득이 상당 부분 여기서 나온다. **표준 스키마로 적어두면 시각화를 새로 만들 필요가 없다.**",
    ],
    related: ["mcap", "foxglove-schema", "rerun", "rviz", "tf"],
    post: { label: "자율주행 시각화", href: "/posts/av-visualization" },
    match: ["Foxglove", "폭스글러브"],
  },
  {
    id: "foxglove-schema",
    term: "Foxglove 표준 스키마",
    category: "도구",
    summary: "시각화 도구가 별도 설정 없이 이해하는 공통 메시지 정의 모음.",
    body: [
      "ROS에 묶이지 않으면서 도구가 알아보게 하려는 시도다. 자주 쓰는 것들:",
      "- `foxglove.PointCloud` — 점군. `fields` 로 x/y/z/intensity/ring/time 을 기술한다.",
      "- `foxglove.RawImage` / `CompressedImage` / `CompressedVideo` — 영상",
      "- `foxglove.CameraCalibration` — K, D, 왜곡 모델, 해상도",
      "- `foxglove.FrameTransform(s)` — 좌표계 사이 변환",
      "- `foxglove.SceneUpdate` / `SceneEntity` — 박스·선·텍스트 프리미티브. **인지 출력을 그리는 표준 통로.**",
      "- `foxglove.Grid` — BEV·점유 격자",
      "- `foxglove.ImageAnnotations` — 이미지 위 2D 박스·점·텍스트",
      "내부 스키마를 따로 쓰더라도, **시각화용 미러 토픽을 표준 스키마로 하나 더 발행**하는 절충이 흔하다.",
    ],
    related: ["foxglove", "mcap", "schema-record", "point-cloud", "camera-calibration"],
    match: ["Foxglove 표준 스키마"],
  },
  {
    id: "rerun",
    term: "Rerun",
    category: "도구",
    summary:
      "Rust로 만든 멀티모달 로깅·시각화 SDK. 코드에서 로그를 흘려보내면 동기화된 3D·2D·시계열 뷰로 스크럽하며 본다.",
    body: [
      "Foxglove가 \"저장된 로그를 여는 뷰어\"라면, Rerun은 **개발 중 코드에 심는 관찰 도구**에 가깝다.",
      "- 엔티티 경로(`world/lidar/points`)에 아키타입(Points3D, Image, Boxes3D, Transform3D…)을 로깅한다.",
      "- **타임라인이 여러 개**다. 프레임 번호로도, 센서 시각으로도, 처리 순서로도 같은 데이터를 훑을 수 있다.",
      "- `.rrd` 파일로 저장해 남에게 보낼 수 있다.",
      "쓰임의 결이 다르다. 파이프라인 중간 텐서, 전처리 결과, 모델이 실제로 본 입력을 **몇 줄로 눈에 띄우는** 데 강하다. 팀 공용 아카이브·리플레이 표준은 MCAP + Foxglove 쪽이다. 경쟁이라기보다 **개발 루프용 / 아카이브용**으로 나뉜다.",
    ],
    related: ["foxglove", "mcap", "rviz"],
    post: { label: "자율주행 시각화", href: "/posts/av-visualization" },
    match: ["Rerun", "rerun"],
  },
  {
    id: "rviz",
    term: "RViz",
    category: "도구",
    summary: "ROS의 고전적인 데스크톱 3D 뷰어. 점군·박스·변환 트리를 실시간으로 본다.",
    body: [
      "ROS 노드에 붙어 토픽을 구독해 그린다. 여전히 현장에서 많이 쓰지만 설치가 필요하고 ROS 환경에 묶이며 링크로 공유하기 어렵다.",
      "이 사이트 라이다 씬의 동심원 거리 링, 원점 축 기즈모 같은 시각 언어가 RViz 계보다.",
    ],
    related: ["foxglove", "rerun", "tf"],
    match: ["RViz"],
  },

  /* ─────────────────────────── 씬·데이터 ─────────────────────────── */
  {
    id: "scene",
    term: "씬 데이터",
    full: "Scene data",
    category: "씬·데이터",
    summary:
      "여러 센서가 같은 순간을 각자의 좌표계로 기록한 것을 시간으로 묶은 덩어리. 자율주행 데이터의 기본 단위.",
    body: [
      "이미지 분류에서는 사진 한 장이 샘플이지만, 자율주행에서는 그럴 수 없다. 신호등을 카메라가 보고, 그 앞 차의 거리를 라이다가 재고, 속도를 레이더가 잰다. **이 셋이 같은 순간의 같은 대상**임을 알아야 판단이 나온다.",
      "그래서 씬은 다음을 하나로 묶는다.",
      "- **동기화된 센서 프레임** — 같은 타임스탬프(오차 수 ms)로 정렬된 라이다 스윕·카메라 이미지·레이더 리턴",
      "- **에고 포즈** — 그 순간 차가 지도상 어디에 어떤 자세로 있었는지",
      "- **캘리브레이션** — 각 센서를 차량 좌표계로 옮기는 변환",
      "- **어노테이션(선택)** — 3D 박스·차선·점유 같은 정답",
      "씬은 여러 감각을 하나의 세계로 합의시키는 **계약서**다.",
    ],
    related: ["sample", "sweep", "ego-pose", "calibration", "mcap", "annotation"],
    post: { label: "씬 데이터란 무엇인가", href: "/posts/av-scene-data" },
    match: ["씬 데이터", "씬(scene)", "scene"],
  },
  {
    id: "sample",
    term: "샘플 / 키프레임",
    full: "sample, keyframe",
    category: "씬·데이터",
    summary: "라벨을 붙일 대표 순간. 모든 프레임에 정답을 달 수는 없어 일정 간격만 고른다.",
    body: [
      "라이다가 10~20Hz로 도는 동안 라벨링은 보통 **2Hz 정도의 키프레임**에만 붙인다. 사람 손이 유한하기 때문이다.",
      "그렇다고 사이 프레임이 쓸모없는 건 아니다. 앞뒤 스윕을 누적하면 성긴 점군이 촘촘해지고 움직임(속도·방향)이 드러난다. 자동 라벨링·보간의 재료도 여기서 나온다.",
      "**\"라벨 없는 프레임 ≠ 쓸모없는 프레임\"** — 이 감각이 AV 데이터 엔지니어링의 출발점이다.",
    ],
    related: ["sweep", "scene", "annotation", "auto-labeling"],
    post: { label: "씬 데이터란 무엇인가", href: "/posts/av-scene-data" },
    match: ["키프레임"],
  },
  {
    id: "sweep",
    term: "스윕",
    full: "sweep",
    category: "씬·데이터",
    summary: "라이다가 한 바퀴 돌며 얻은 점군 한 세트. 회전형 라이다의 프레임 단위.",
    body: [
      "회전형 라이다는 10Hz면 100ms에 걸쳐 한 바퀴를 돈다. 즉 **한 스윕 안의 점들은 서로 다른 시각에 찍혔다.** 60km/h로 달리는 동안 한 바퀴면 차가 1.7m를 움직인다.",
      "그래서 점군 메시지에는 점별 상대 시각(`time` 필드)이 들어가야 하고, 이걸로 **모션 보정**을 해야 형상이 뭉개지지 않는다. 이 필드를 빼고 로그를 설계하면 나중에 되돌릴 수 없다.",
    ],
    related: ["point-cloud", "motion-compensation", "sample", "log-time"],
    match: ["스윕"],
  },
  {
    id: "ego-pose",
    term: "에고 포즈",
    full: "ego pose",
    category: "씬·데이터",
    summary: "그 순간 자기 차가 지도(월드) 좌표계 어디에 어떤 자세로 있었는지.",
    body: [
      "위치(x, y, z)와 자세(보통 쿼터니언)의 묶음이다. GNSS/IMU와 라이다 정합(SLAM/localization)을 합쳐 만든다.",
      "왜 중요한가 — 센서 좌표계의 값을 **여러 시점에 걸쳐 하나의 세계로 쌓으려면** 에고 포즈가 있어야 한다. 앞뒤 스윕 누적, 정지 물체 판별(상대 속도에서 자기 속도를 빼야 한다), 지도 정합이 전부 여기 걸린다.",
      "포즈의 정확도가 라벨 품질의 상한이다. 포즈가 흔들리면 누적 점군이 두 겹으로 보이고, 사람이 그 위에 박스를 그리면 그 오차가 정답에 그대로 박힌다.",
    ],
    related: ["scene", "tf", "gnss", "calibration"],
    post: { label: "3D 기하 기초", href: "/posts/av-3d-geometry" },
    match: ["에고 포즈", "ego pose"],
  },
  {
    id: "tf",
    term: "좌표 변환 트리",
    full: "transform tree, tf",
    category: "센서·좌표",
    summary: "`map → odom → base_link → lidar_top` 처럼 좌표계를 부모-자식으로 잇는 구조. 임의의 두 좌표계 사이 변환을 합성으로 얻는다.",
    body: [
      "ROS의 `tf` 가 원조이고, MCAP에서는 `foxglove.FrameTransform` 메시지로 같은 일을 한다. 두 종류가 있다.",
      "- **정적 변환(`/tf_static`)** — 센서 장착 위치처럼 주행 중 변하지 않는 것. 로그 앞부분에 한 번 적는다.",
      "- **동적 변환(`/tf`)** — 차의 움직임처럼 계속 바뀌는 것. 매 프레임 적는다.",
      "실무 함정: 변환을 조회할 때는 **그 시각의** 변환을 써야 한다. \"가장 최근 변환\"을 쓰면 고속 주행에서 수십 cm가 밀린다. 라이다 점의 캡처 시각으로 보간(interpolate)해 조회하는 게 정석이다.",
      "로그에 tf가 없으면 시각화 도구가 센서를 한 공간에 겹치지 못한다. **MCAP 전환에서 반드시 챙겨야 하는 토픽**이다.",
    ],
    related: ["calibration", "ego-pose", "foxglove-schema", "extrinsic"],
    match: ["좌표 변환 트리", "tf 트리", "좌표 변환"],
  },
  {
    id: "calibration",
    term: "캘리브레이션",
    full: "sensor calibration",
    category: "센서·좌표",
    summary: "센서의 내부 특성과 센서 사이의 위치·자세, 그리고 시간축을 정렬하는 작업.",
    body: [
      "여러 센서를 겹쳐 쓰는 순간 \"같은 대상을 같은 위치로 보고 있는가\"가 모든 것을 가른다. 세 축이 있다.",
      "- **내부(intrinsic)** — 카메라 초점거리·주점·왜곡 계수, 라이다 빔별 각도 오프셋",
      "- **외부(extrinsic)** — 센서 좌표계 → 차량 좌표계 강체 변환(회전 R, 이동 t)",
      "- **시간(temporal)** — 센서들의 시계 정렬과 트리거 지연",
      "0.5° 어긋난 외부 파라미터는 50m 거리에서 40cm 밀린다. 그리고 캘리브레이션은 **한 번 하고 끝이 아니다** — 진동·온도·사고·정비로 계속 변한다. 그래서 값이 아니라 **씬을 따라다니는 버전 붙은 메타데이터**로 다뤄야 한다.",
    ],
    related: ["intrinsic", "extrinsic", "tf", "time-sync", "attachment"],
    post: { label: "센서 캘리브레이션", href: "/posts/av-calibration" },
    match: ["캘리브레이션"],
  },
  {
    id: "intrinsic",
    term: "내부 파라미터",
    full: "intrinsic parameters",
    category: "센서·좌표",
    summary: "3D 점이 그 카메라의 2D 픽셀로 찍히는 규칙. 카메라 행렬 K와 왜곡 계수.",
    body: [
      "`K` 는 초점거리 `fx, fy` 와 주점 `cx, cy` 로 이뤄진 3×3 행렬이다. 여기에 렌즈가 직선을 휘게 하는 **왜곡 계수**가 따라붙는다.",
      "`K` 가 틀리면 픽셀 좌표와 실제 광선 방향이 어긋난다. 라이다 점을 이미지에 투영할 때 가장 먼저 드러난다 — 점들이 물체에서 미끄러진다.",
      "해상도를 바꾸면 `K` 도 같이 스케일해야 한다. 학습 전처리에서 이미지를 리사이즈·크롭하고 `K` 를 안 고치는 건 흔한 버그다.",
    ],
    related: ["calibration", "distorted-image", "camera-calibration", "extrinsic"],
    post: { label: "센서 캘리브레이션", href: "/posts/av-calibration" },
    match: ["내부 파라미터", "intrinsic"],
  },
  {
    id: "extrinsic",
    term: "외부 파라미터",
    full: "extrinsic parameters",
    category: "센서·좌표",
    summary: "한 센서 좌표계를 다른 좌표계(보통 차량 기준)로 옮기는 강체 변환. 회전 R과 이동 t.",
    body: [
      "4×4 동차 변환 행렬로 묶어 쓴다. 라이다 점을 차량 좌표계로, 다시 에고 포즈로 월드 좌표계로 올리는 사슬의 각 고리가 이것이다.",
      "각도 오차가 거리에 비례해 커진다는 점이 핵심이다. 0.5°는 10m에서 9cm, 50m에서 44cm다. 원거리 검출 성능이 이유 없이 나쁘면 외부 파라미터를 먼저 의심한다.",
    ],
    related: ["calibration", "intrinsic", "tf", "ego-pose"],
    post: { label: "센서 캘리브레이션", href: "/posts/av-calibration" },
    match: ["외부 파라미터", "extrinsic"],
  },
  {
    id: "time-sync",
    term: "시간 동기화",
    full: "time synchronization",
    category: "센서·좌표",
    summary: "여러 센서의 시계를 같은 기준에 맞추는 일. 융합의 전제 조건.",
    body: [
      "60km/h는 초당 16.7m다. **10ms 어긋나면 17cm**가 밀린다. 카메라와 라이다가 서로 다른 순간의 세상을 보고 있으면, 아무리 캘리브레이션이 정확해도 박스가 물체에서 벗어난다.",
      "수단은 계층적이다 — GNSS의 PPS(초당 펄스)를 기준으로 PTP(정밀시간프로토콜)로 네트워크 시계를 맞추고, 센서 트리거를 하드웨어로 동기화한다.",
      "데이터 쪽에서 반드시 해야 할 일은 **어느 시계로 적힌 값인지 스키마에 명시**하는 것이다. 기록 시각(log_time)과 캡처 시각을 섞으면 조용히 틀린 학습 데이터가 만들어진다.",
    ],
    related: ["log-time", "ptp", "sensor-fusion", "calibration"],
    match: ["시간 동기화"],
  },
  {
    id: "ptp",
    term: "PTP",
    full: "Precision Time Protocol (IEEE 1588)",
    category: "센서·좌표",
    summary: "네트워크로 연결된 장치들의 시계를 마이크로초 수준으로 맞추는 프로토콜.",
    body: [
      "NTP가 밀리초 수준이라면 PTP는 마이크로초 수준을 노린다. 차량 이더넷으로 연결된 라이다·카메라·컴퓨트가 같은 시계를 공유하게 하는 표준 수단이다.",
      "보통 GNSS 수신기가 그랜드마스터가 되어 UTC를 물어오고, 스위치와 센서가 여기에 정렬한다.",
    ],
    related: ["time-sync", "gnss"],
    match: ["PTP"],
  },
  {
    id: "gnss",
    term: "GNSS / IMU",
    full: "Global Navigation Satellite System / Inertial Measurement Unit",
    category: "센서·좌표",
    summary: "차가 지구 어디에서 어떤 자세로 어떻게 움직이는지 알려주는 센서 조합.",
    body: [
      "- **GNSS** — 위성으로 절대 위치. 느리고(1~10Hz) 도심 협곡·터널에서 끊긴다. RTK 보정을 쓰면 cm급까지 간다.",
      "- **IMU** — 가속도계·자이로로 100~1000Hz 상대 운동. 빠르지만 적분하면 오차가 누적(드리프트)된다.",
      "둘을 칼만 필터류로 융합하고, 라이다 정합까지 얹어 **에고 포즈**를 만든다. 서로의 약점을 정확히 메우는 고전적인 예다.",
    ],
    related: ["ego-pose", "sensor-fusion", "ptp"],
    match: ["GNSS", "IMU"],
  },
  {
    id: "can",
    term: "CAN",
    full: "Controller Area Network",
    category: "센서·좌표",
    summary: "차량 내부 ECU들이 주고받는 통신 버스. 조향각·휠속·페달·기어 같은 실제 차량 상태가 흐른다.",
    body: [
      "인지 데이터에 가려 소홀히 다뤄지지만, **정답에 가장 가까운 신호**가 여기 있다. 사람이 실제로 어떻게 조향하고 가감속했는가 — 모방학습·E2E·VLA의 행동 라벨이 결국 CAN에서 나온다.",
      "로그 설계에서 챙길 것: 원시 CAN 프레임을 그대로 담을 것인가, DBC로 디코딩한 물리량으로 담을 것인가. **둘 다 담는 게 안전하다.** 원시는 재해석 여지를 남기고, 디코딩본은 분석을 즉시 가능하게 한다.",
    ],
    related: ["vla", "control", "mcap", "topic"],
    match: ["CAN"],
  },
  {
    id: "point-cloud",
    term: "포인트 클라우드",
    full: "point cloud",
    category: "씬·데이터",
    summary: "정렬되지 않은 3D 점들의 집합. 라이다의 기본 출력 형태.",
    body: [
      "점마다 `x, y, z` 와 함께 여러 속성이 붙는다. 로그 스키마를 짤 때 무엇을 남길지가 나중을 좌우한다.",
      "- **intensity(반사 강도)** — 차선 도색, 표지판, 젖은 노면 판별에 쓰인다.",
      "- **ring / laser_id** — 몇 번째 빔인지. 지면 제거와 거리 이미지 변환에 필요하다.",
      "- **time(점별 상대 시각)** — 모션 보정의 필수 입력.",
      "- **return type** — 1st/2nd/strongest. 비·먼지·유리 판별에 쓰인다.",
      "\"x, y, z만 남기고 버렸다\"는 결정은 되돌릴 수 없다. **원본 로그에서는 다 남겨야 한다.**",
    ],
    related: ["sweep", "motion-compensation", "voxel", "foxglove-schema"],
    post: { label: "3D 데이터 표현", href: "/posts/av-3d-data" },
    match: ["포인트 클라우드", "점군"],
  },
  {
    id: "motion-compensation",
    term: "모션 보정",
    full: "motion compensation, deskew",
    category: "센서·좌표",
    summary: "회전 라이다 한 스윕 안에서 차가 움직인 만큼을 되돌려, 점들을 같은 순간의 좌표계로 맞추는 보정.",
    body: [
      "10Hz 라이다는 한 바퀴에 100ms가 걸린다. 그동안 차가 움직였으므로, 스윕 시작에 찍힌 점과 끝에 찍힌 점은 **다른 원점에서 본 값**이다. 보정하지 않으면 벽이 휘고 차가 늘어난다.",
      "방법은 단순하다. 점별 시각으로 에고 포즈를 보간해, 각 점을 스윕 기준 시각의 좌표계로 옮긴다.",
      "그래서 필요한 재료가 **점별 타임스탬프 + 고주파 에고 포즈**다. 둘 중 하나만 없어도 보정을 할 수 없고, 이건 기록 단계에서 결정된다.",
    ],
    related: ["sweep", "point-cloud", "ego-pose", "tf"],
    match: ["모션 보정"],
  },

  /* ─────────────────────────── 카메라·영상 ─────────────────────────── */
  {
    id: "distorted-image",
    term: "왜곡 이미지",
    full: "distorted image",
    category: "카메라·영상",
    summary: "렌즈 왜곡이 보정되지 않은 원본 이미지. 직선이 화면 가장자리에서 휘어 보인다.",
    body: [
      "이상적인 핀홀 카메라는 직선을 직선으로 찍지만, 실제 렌즈는 그렇지 않다. 두 종류가 섞인다.",
      "- **방사 왜곡(radial)** — 중심에서 멀수록 휜다. 통 모양으로 부풀면 배럴, 오므라들면 핀쿠션. 계수 `k1, k2, k3`.",
      "- **접선 왜곡(tangential)** — 렌즈와 센서가 완벽히 평행하지 않아 생긴다. 계수 `p1, p2`.",
      "**왜 실무에서 계속 걸리는가** — 라이다 점을 이미지에 투영하거나 2D 박스를 3D로 올릴 때, `K` 만 쓰고 왜곡 계수 `D` 를 빼먹으면 화면 중앙은 맞는데 **가장자리에서 수십 픽셀이 밀린다.** 중앙만 보고 \"캘리브레이션 잘 맞네\" 하고 넘어가는 사고가 흔하다.",
      "그리고 **라벨이 어느 이미지 위에 그려졌는지**가 메타데이터로 남아야 한다. 왜곡 이미지 위 박스와 보정 이미지 위 박스는 좌표가 다르다. 이걸 안 적어두면 두 배치의 라벨이 조용히 섞인다.",
    ],
    related: ["undistortion", "fisheye", "intrinsic", "camera-calibration", "rectification"],
    post: { label: "카메라 이미지의 실제", href: "/posts/av-camera-image" },
    match: ["왜곡 이미지", "distorted image", "distorted"],
  },
  {
    id: "undistortion",
    term: "왜곡 보정",
    full: "undistortion",
    category: "카메라·영상",
    summary: "왜곡 계수를 이용해 렌즈 왜곡을 되돌린, 핀홀 모델에 맞는 이미지를 만드는 것.",
    body: [
      "공짜가 아니다. 대가가 셋 있다.",
      "- **화각 손실 또는 검은 여백** — 휜 상을 펴면 가장자리가 잘리거나 빈다.",
      "- **리샘플링 손실** — 보간이 들어가 미세 질감이 뭉개진다. 원거리 소형 객체(신호등!)에 불리하다.",
      "- **광각에서는 아예 불가능에 가깝다** — 화각이 120°를 넘으면 핀홀 평면으로 펴는 순간 가장자리가 무한대로 늘어난다.",
      "그래서 팀에 따라 **왜곡 이미지 위에서 그대로 학습·라벨링**하고, 필요할 때만 광선 방향으로 변환하는 방식을 택한다. 어느 쪽이든 **일관성이 정확도보다 중요하다** — 학습·라벨·추론이 같은 이미지 공간에 있어야 한다.",
    ],
    related: ["distorted-image", "fisheye", "rectification", "intrinsic"],
    post: { label: "카메라 이미지의 실제", href: "/posts/av-camera-image" },
    match: ["왜곡 보정", "undistort"],
  },
  {
    id: "rectification",
    term: "정류",
    full: "rectification",
    category: "카메라·영상",
    summary: "스테레오 두 이미지를 같은 평면에 정렬해, 대응점이 같은 가로줄에 오게 만드는 변환.",
    body: [
      "왜곡 보정과 자주 혼동되지만 다른 일이다. 왜곡 보정은 **렌즈의 휨**을 펴고, 정류는 **두 카메라의 상대 자세**를 정렬한다.",
      "정류하면 스테레오 매칭이 1차원 탐색으로 줄어 깊이 추정이 훨씬 싸진다. ROS `CameraInfo` 의 `R`(정류 회전)과 `P`(정류 후 투영 행렬)가 이 정보를 담는다.",
    ],
    related: ["undistortion", "distorted-image", "camera-calibration"],
    match: ["정류(rectification)", "rectification", "정류"],
  },
  {
    id: "fisheye",
    term: "어안 렌즈",
    full: "fisheye",
    category: "카메라·영상",
    summary: "화각 180° 안팎까지 담는 초광각 렌즈. 주차·근거리 인지에서 필수이지만 핀홀 모델로는 다룰 수 없다.",
    body: [
      "일반 핀홀 + rad-tan 왜곡 모델로는 표현이 안 된다. 별도의 투영 모델을 쓴다 — **등거리(equidistant) / Kannala-Brandt(`k1~k4`)**, MEI, 이중구(double sphere) 등.",
      "차량에는 보통 전후좌우 4개가 달리고, 이걸 지면 평면으로 투영해 이어 붙이면 **AVM(어라운드뷰)** BEV 이미지가 된다. 주차 슬롯 검출(PSD)이 이 위에서 돌아간다.",
      "데이터 관점의 함정: 왜곡 모델 종류를 메시지에 안 적으면 나중에 아무도 정확히 복원할 수 없다. `distortion_model` 필드는 반드시 채워야 한다.",
    ],
    related: ["distorted-image", "psd", "camera-calibration", "bev"],
    post: { label: "카메라 이미지의 실제", href: "/posts/av-camera-image" },
    match: ["어안", "fisheye"],
  },
  {
    id: "camera-calibration",
    term: "CameraInfo / CameraCalibration",
    category: "카메라·영상",
    summary: "이미지 한 장을 기하학적으로 해석하는 데 필요한 값 묶음. K, D, 왜곡 모델, 해상도, (스테레오면) R·P.",
    body: [
      "ROS의 `sensor_msgs/CameraInfo`, Foxglove의 `foxglove.CameraCalibration` 이 같은 역할을 한다.",
      "- `K` — 3×3 카메라 행렬",
      "- `D` — 왜곡 계수 배열 (모델마다 길이가 다르다)",
      "- `distortion_model` — `plumb_bob`, `rational_polynomial`, `equidistant` 등",
      "- `width`, `height` — 이 K가 유효한 해상도",
      "- `frame_id` — 어느 좌표계의 카메라인가",
      "**이미지 토픽 옆에 이 토픽을 반드시 함께 기록해야 한다.** 이미지만 있는 로그는 3년 뒤에 기하 정보를 못 살린다. 정적이라도 주기적으로(또는 로그 시작마다) 발행하는 게 안전하다.",
    ],
    related: ["intrinsic", "distorted-image", "foxglove-schema", "attachment"],
    match: ["CameraInfo", "CameraCalibration"],
  },
  {
    id: "compressed-image",
    term: "이미지 압축 / 비디오 코덱",
    category: "카메라·영상",
    summary: "로그에 영상을 담는 방식 선택. Raw · JPEG · H.264/265 사이에서 용량과 화질과 디코딩 비용을 맞바꾼다.",
    body: [
      "카메라 8대 × 30fps × 2MP를 raw로 담으면 시간당 수 TB다. 현실적으로 선택은 이렇다.",
      "- **RawImage** — 무손실. 저조도 노이즈 연구나 ISP 검증처럼 원본이 필요한 경우에만.",
      "- **JPEG(CompressedImage)** — 프레임 독립적이라 임의 프레임 접근이 쉽다. 라벨링·학습 파이프라인에 편하다. 10~20배 축소.",
      "- **H.264/H.265(CompressedVideo)** — 프레임 간 예측으로 훨씬 작다(50~100배). 대신 **임의 프레임을 뽑으려면 키프레임부터 디코딩**해야 해서 랜덤 액세스가 비싸다.",
      "실무 절충: 아카이브는 H.264, 학습용으로 뽑아낸 키프레임은 JPEG. 그리고 **압축 아티팩트가 모델 성능에 미치는 영향을 한 번은 측정**해두는 게 좋다 — 특히 원거리 신호등처럼 작은 객체에서.",
      "이미 압축된 페이로드에 MCAP 청크 압축을 또 거는 건 이득이 거의 없다.",
    ],
    related: ["training-io", "zstd", "isp", "foxglove-schema"],
    match: ["이미지 압축", "H.264"],
  },
  {
    id: "isp",
    term: "ISP",
    full: "Image Signal Processor",
    category: "카메라·영상",
    summary: "센서의 raw 신호를 사람이 보는 이미지로 만드는 처리 사슬. 디모자이킹·노출·톤매핑·노이즈 제거.",
    body: [
      "카메라 이미지 파일은 이미 **여러 단계 가공된 결과물**이다. 베이어 패턴 raw → 디모자이킹 → 화이트밸런스 → 톤매핑 → 샤프닝 → 인코딩.",
      "왜 데이터 사람이 알아야 하는가 — **ISP 설정이 바뀌면 같은 세상이 다른 픽셀로 찍힌다.** 차량 소프트웨어 업데이트로 톤매핑이 바뀌면, 그 전후 데이터로 학습한 모델의 성능이 설명 없이 갈린다.",
      "그래서 ISP 버전·설정을 로그 메타데이터에 박아야 한다. 이건 캘리브레이션 버전과 같은 성격의 정보다.",
      "고동적범위(HDR) 처리도 여기 속한다. 터널 출구처럼 명암비가 극단적인 장면에서 무엇이 날아가는지가 여기서 정해진다.",
    ],
    related: ["compressed-image", "metadata-record", "rolling-shutter"],
    match: ["ISP"],
  },
  {
    id: "rolling-shutter",
    term: "롤링 셔터",
    full: "rolling shutter",
    category: "카메라·영상",
    summary: "이미지를 한 번에 찍지 않고 위에서 아래로 줄 단위로 읽는 방식. 빠른 움직임에서 상이 기울어진다.",
    body: [
      "한 장의 이미지가 **여러 시각에 걸쳐** 만들어진다는 뜻이다. 라이다 스윕과 같은 문제다.",
      "고속에서 세로 기둥이 기울어 보이고, 라이다 점을 투영하면 화면 위/아래에서 서로 다른 만큼 어긋난다. 정밀한 융합에서는 줄별 시각을 고려한 보정이 필요하다.",
      "글로벌 셔터 센서는 이 문제가 없지만 비싸다. **어느 쪽인지 로그 메타에 적어둬야** 나중에 오차의 출처를 설명할 수 있다.",
    ],
    related: ["motion-compensation", "time-sync", "isp"],
    match: ["롤링 셔터", "rolling shutter"],
  },

  /* ─────────────────────────── 어노테이션 ─────────────────────────── */
  {
    id: "annotation",
    term: "어노테이션 데이터",
    full: "annotation data",
    category: "어노테이션",
    summary:
      "센서 데이터에 붙인 정답(ground truth). 무엇이 어디에 있고 무엇인지 사람 또는 자동 파이프라인이 표시한 것.",
    body: [
      "센서 데이터가 \"세상이 어떻게 보였는가\"라면, 어노테이션은 **\"그 안에 무엇이 있었는가\"** 다. 학습의 교사이자 평가의 자다.",
      "형태는 태스크마다 다르다 — 2D 박스, 3D 큐보이드, 폴리라인(차선), 폴리곤(노면 표시), 세그멘테이션 마스크, 점유 복셀, 궤적, 속성(가려짐·잘림·신호등 색), 트랙 id.",
      "**핵심 성질 셋**을 기억하면 된다.",
      "- **비싸다** — 3D 큐보이드 하나에 사람 손이 들어간다. 그래서 무엇을 라벨링할지 고르는 큐레이션이 중요해진다.",
      "- **틀린다** — 사람도 애매한 경계에서 갈린다. 라벨 노이즈는 모델 성능의 상한을 직접 깎는다.",
      "- **버전이 있다** — 라벨 스펙(온톨로지·규칙)이 바뀌면 과거 라벨과 새 라벨이 섞여 조용히 성능을 망친다.",
      "그래서 어노테이션은 \"한 번 만드는 자산\"이 아니라 **스펙·버전·품질지표를 갖춘 지속 관리 대상**이다.",
    ],
    related: ["cuboid", "ontology", "auto-labeling", "label-quality", "sample", "curation"],
    post: { label: "어노테이션 데이터", href: "/posts/av-annotation-data" },
    match: ["어노테이션", "annotation data"],
  },
  {
    id: "cuboid",
    term: "3D 큐보이드",
    full: "3D cuboid / bounding box",
    category: "어노테이션",
    summary: "객체를 감싸는 방향 있는 3D 직육면체. 중심(x,y,z), 크기(w,l,h), 방향(yaw)으로 적는다.",
    body: [
      "3D 객체 검출(3DOD)의 정답 형식이다. 실무 스펙에는 좌표 말고도 붙는 게 많다.",
      "- **클래스** — car, truck, bus, pedestrian, cyclist…",
      "- **트랙 id** — 프레임을 넘어 같은 객체임을 잇는 식별자",
      "- **가려짐·잘림 정도** — 평가에서 난이도를 나누는 기준",
      "- **점 개수** — 박스 안 라이다 점 수. 너무 적으면 평가에서 제외하는 규칙을 둔다",
      "- **속도** — 인접 키프레임 사이 위치 차이에서 유도",
      "주의할 점은 **어느 좌표계에 적혔는가**다. 센서 좌표계인지 차량 좌표계인지 월드인지, yaw의 0도가 어느 축인지 — 데이터셋마다 다르다. 여러 소스를 한 파이프라인에 섞을 때 첫 번째로 부딪히는 벽이다.",
    ],
    related: ["annotation", "3dod", "track-id", "extrinsic"],
    post: { label: "3D 객체 검출", href: "/posts/av-3d-object-detection" },
    match: ["큐보이드", "cuboid"],
  },
  {
    id: "track-id",
    term: "트랙 ID",
    full: "track id, instance id",
    category: "어노테이션",
    summary: "프레임이 바뀌어도 같은 객체임을 잇는 식별자. 속도·궤적 라벨의 전제.",
    body: [
      "한 프레임의 박스만으로는 속도를 알 수 없다. 트랙 id가 있어야 \"이 차가 3프레임 동안 이렇게 움직였다\"가 되고, 거기서 속도와 미래 궤적 정답이 나온다.",
      "라벨링에서 가장 깨지기 쉬운 부분이기도 하다 — 객체가 잠깐 가려졌다 나타났을 때 같은 id를 유지하는가(**id switch**). 추적(MOT) 평가 지표가 이걸 별도로 센다.",
    ],
    related: ["cuboid", "tracking", "trajectory", "annotation"],
    match: ["트랙 ID", "트랙 id", "track id"],
  },
  {
    id: "segmentation",
    term: "세그멘테이션",
    full: "semantic / instance / panoptic segmentation",
    category: "어노테이션",
    summary: "픽셀 또는 점 하나하나에 클래스를 붙이는 라벨. 박스로는 표현 못 하는 형상을 담는다.",
    body: [
      "- **시맨틱** — 픽셀마다 클래스만. 같은 클래스의 두 객체를 구분하지 않는다.",
      "- **인스턴스** — 객체 단위로 분리. \"이 차\"와 \"저 차\"를 나눈다.",
      "- **파놉틱** — 둘을 합친 것. 셀 수 있는 것(thing)은 인스턴스로, 셀 수 없는 것(도로·하늘·건물, stuff)은 시맨틱으로.",
      "라이다 점군에도 똑같이 적용된다(점별 클래스). 노면·차선·주행 가능 영역처럼 **박스가 어울리지 않는 대상**의 정답 형식이다.",
      "비용이 크다. 그래서 실무는 자동 세그멘테이션 + 사람 수정의 조합으로 간다.",
    ],
    related: ["annotation", "lmgi", "freespace", "occ"],
    match: ["세그멘테이션", "segmentation"],
  },
  {
    id: "ontology",
    term: "온톨로지 / 라벨 스펙",
    full: "ontology, taxonomy, labeling spec",
    category: "어노테이션",
    summary: "무엇을 어떤 클래스로, 어떤 규칙으로 라벨링할지 정한 문서. 데이터셋의 헌법.",
    body: [
      "\"자전거를 끌고 가는 사람은 보행자인가 자전거인가\", \"트레일러는 트럭과 한 박스인가 두 박스인가\", \"20m 밖 가려진 차도 라벨링하는가\" — 이런 결정의 모음이다.",
      "여기서 흔한 실패가 둘이다.",
      "- **스펙이 문서로만 있고 검증되지 않는다** → 라벨러마다 다르게 해석해 노이즈가 된다. 경계 사례 예시 이미지가 있는 스펙이 훨씬 낫다.",
      "- **스펙 변경에 버전을 안 붙인다** → 6개월 전 라벨과 지금 라벨이 다른 규칙을 따르는데 같은 테이블에 섞인다. 성능 회귀의 원인을 영영 못 찾는다.",
      "**라벨 스펙 버전은 데이터 스냅샷 버전과 함께 모델에 못 박아야 한다.**",
    ],
    related: ["annotation", "label-quality", "data-versioning"],
    match: ["온톨로지", "라벨 스펙"],
  },
  {
    id: "auto-labeling",
    term: "오토라벨링",
    full: "auto-labeling, pre-annotation",
    category: "어노테이션",
    summary: "모델이 먼저 라벨을 만들고 사람이 고치는 방식. 라벨 비용을 몇 배로 줄이는 표준 수법.",
    body: [
      "핵심 아이디어는 **오프라인은 온라인보다 유리하다**는 것이다. 차에서 도는 모델은 실시간·현재 프레임만 쓸 수 있지만, 라벨을 만드는 모델은 시간 제약이 없고 **미래 프레임도 볼 수 있다.**",
      "그래서 오프라인 자동 라벨러는 훨씬 무거운 모델을 쓰고, 앞뒤 프레임을 모아 점군을 누적하고, 궤적을 전후로 매끄럽게 다듬는다. 사람보다 일관되고 사람보다 싸다.",
      "실무 형태는 대체로 이렇다 — **자동 생성 → 신뢰도 낮은 것만 사람에게 → 사람 수정본으로 자동 라벨러 재학습.**",
      "위험은 **자기 확증**이다. 자동 라벨이 모델의 편향을 그대로 물려주면, 모델은 자기가 이미 잘하는 것만 더 잘하게 된다. 사람이 검수하는 샘플을 무작위로도 섞어야 하는 이유다.",
    ],
    related: ["annotation", "label-quality", "curation", "sample"],
    post: { label: "어노테이션 데이터", href: "/posts/av-annotation-data" },
    match: ["오토라벨링", "자동 라벨링", "auto-labeling"],
  },
  {
    id: "label-quality",
    term: "라벨 품질",
    category: "어노테이션",
    summary: "정답이 얼마나 정확하고 일관된가. 모델 성능의 천장을 결정한다.",
    body: [
      "측정 수단이 있어야 관리가 된다.",
      "- **합의도(IAA)** — 같은 장면을 두 사람이 라벨링해 얼마나 일치하는지. 스펙이 모호한 지점을 드러낸다.",
      "- **골든셋** — 전문가가 만든 소량의 정밀 정답. 라벨러와 자동 라벨러를 이걸로 채점한다.",
      "- **감사 샘플링** — 납품 배치에서 무작위로 뽑아 검수. 통과 기준을 미리 정해둔다.",
      "- **일관성 검사** — 트랙이 갑자기 끊기거나, 박스 크기가 프레임마다 튀거나, 도로 밖에 차가 있는 등 규칙 위반 자동 탐지.",
      "\"라벨은 정답이니까 맞다\"는 가정이 가장 비싼 실수다. 평가 세트의 라벨이 틀리면 **틀린 방향으로 최적화된다.**",
    ],
    related: ["annotation", "ontology", "auto-labeling", "map-metric"],
    match: ["라벨 품질"],
  },

  /* ─────────────────────────── 인지 태스크 ─────────────────────────── */
  {
    id: "3dod",
    term: "3DOD",
    full: "3D Object Detection",
    category: "인지 태스크",
    summary: "주변 물체를 위치·크기·방향·속도를 가진 3D 박스로 잡아내는 태스크.",
    body: [
      "2D 박스는 \"화면 어디\"만 알려주지만 운전은 \"공간 어디\"를 요구한다. 3DOD의 출력은 각 객체에 대해 중심·크기·yaw·클래스·신뢰도, 보통 속도까지다.",
      "접근은 크게 셋이다.",
      "- **라이다 기반** — PointPillars, CenterPoint 계열. 거리가 정확하다.",
      "- **카메라 기반** — 여러 카메라를 BEV로 올려 검출(BEVFormer, LSS 계열). 싸고 의미 정보가 풍부하지만 깊이가 약하다.",
      "- **융합** — 둘을 BEV 특징 단계에서 합친다.",
      "한계가 분명하다. **정의된 클래스만 잡는다.** 도로에 떨어진 사다리, 처음 보는 형상은 박스로 안 나온다 — 그래서 점유(OCC)가 필요해진다.",
    ],
    related: ["cuboid", "occ", "bev", "sensor-fusion", "map-metric"],
    post: { label: "3D 객체 검출", href: "/posts/av-3d-object-detection" },
    match: ["3DOD", "3D 객체 검출"],
  },
  {
    id: "occ",
    term: "OCC",
    full: "Occupancy / Occupancy Prediction",
    category: "인지 태스크",
    summary: "세상을 작은 3D 칸(복셀)으로 나눠 각 칸이 차 있는지를 직접 예측하는 태스크. 클래스를 몰라도 부피를 안다.",
    body: [
      "3D 박스가 \"아는 물체\"만 잡는 데 비해, 점유는 **형상 자체**를 다룬다. 도로에 떨어진 적재물, 공사 자재, 누운 나무 — 클래스가 없어도 \"저기에 뭔가 있다\"를 말할 수 있다.",
      "출력은 보통 BEV 격자에 높이 축을 얹은 3D 텐서다(예: 전후좌우 100m를 0.4m 칸으로, 높이 16칸). 각 칸에 대해,",
      "- **점유 여부** — 차 있는가 / 비었는가 / 관측되지 않았는가(**미관측은 빈 것과 다르다**)",
      "- **시맨틱 점유** — 칸마다 클래스까지 (도로·차량·식생·건물…)",
      "- **4D 점유 / flow** — 각 칸이 다음 순간 어디로 움직이는지",
      "박스와 배타적이지 않다. 실무는 둘을 같이 쓴다 — 아는 것은 박스로 추적하고, 모르는 것은 점유로 피한다.",
      "데이터 쪽 부담이 크다. 정답 점유는 사람이 그리지 않고 **누적 점군에서 자동 생성**하는 게 일반적이고, 그래서 에고 포즈 정확도와 모션 보정 품질이 그대로 라벨 품질이 된다.",
    ],
    related: ["3dod", "voxel", "bev", "freespace", "long-tail"],
    post: { label: "점유 예측", href: "/posts/av-occupancy" },
    match: ["OCC", "점유 예측", "점유(occupancy)"],
  },
  {
    id: "psd",
    term: "PSD",
    full: "Parking Slot Detection",
    category: "인지 태스크",
    summary: "주차 공간을 찾아내는 태스크. 슬롯의 꼭짓점과 유형, 비어 있는지 여부를 낸다.",
    body: [
      "자동 주차(APA)나 원격/기억 주차(HPP)의 인지 입력이다. 일반 전방 카메라가 아니라 **어안 카메라 4개를 지면으로 투영해 이어 붙인 AVM(어라운드뷰) BEV 이미지** 위에서 도는 게 보통이다. 주차선은 차 바로 옆 지면에 있어서 전방 시야로는 안 보이기 때문이다.",
      "출력·라벨 형식은 대체로 이렇다.",
      "- **마킹 포인트** — 주차선이 만드는 꼭짓점(보통 입구 두 점 + 안쪽 두 점)",
      "- **슬롯 유형** — 수직(직각)·평행(병렬)·대각",
      "- **점유 상태** — 비었는가, 차가 있는가",
      "- **부가 속성** — 장애인/전기차 전용, 기둥·연석에 막힘, 진입 가능 방향",
      "어려운 지점은 인지 자체보다 **환경**이다. 지하주차장의 낮은 조도와 반사, 지워진 도색, 기둥에 가린 꼭짓점, 어안 왜곡의 잔차. 그리고 슬롯이 실제로 비었는지는 카메라만으로 애매해서 초음파·라이다와 융합하는 경우가 많다.",
    ],
    related: ["fisheye", "bev", "sensor-fusion", "annotation"],
    post: { label: "인지 태스크 지도", href: "/posts/av-perception-tasks" },
    match: ["PSD"],
  },
  {
    id: "tld",
    term: "TLD",
    full: "Traffic Light Detection (and Recognition)",
    category: "인지 태스크",
    summary: "신호등을 찾고, 색·화살표 상태를 읽고, 그중 어느 것이 내 차선에 해당하는지 연결하는 태스크.",
    body: [
      "세 단계가 겹쳐 있고, 실무에서 진짜 어려운 건 세 번째다.",
      "- **검출** — 이미지에서 신호등 박스를 찾는다. 100m 밖이면 몇 픽셀짜리 객체다.",
      "- **인식** — 색(적·황·녹), 화살표 방향, 점멸 상태를 읽는다.",
      "- **연관(association)** — 교차로에 신호등이 6개 보일 때 **내 차선에 적용되는 건 어느 것인가.** 이게 틀리면 나머지가 다 맞아도 사고다.",
      "연관은 보통 순수 인지로 풀지 않고 **HD 맵에 저장된 신호등 위치와 차선의 대응 관계**를 이용한다. 지도의 3D 위치를 현재 카메라에 투영해 검출과 매칭한다. 그래서 TLD 품질은 지도·측위 정확도에 묶여 있다.",
      "센서 쪽 함정들: 역광과 블루밍, LED 신호등의 **PWM 점멸과 카메라 셔터 간섭**(특정 노출에서 꺼진 것처럼 찍힘), 야간 번짐, 우천 시 렌즈 물방울. 그래서 신호등용 카메라는 노출을 따로 잡거나 전용 카메라를 두기도 한다.",
      "데이터 쪽 함정: 신호가 바뀌는 **전이 프레임**의 정답을 무엇으로 할지 스펙에 없으면 라벨이 갈린다.",
    ],
    related: ["hd-map", "annotation", "isp", "compressed-image"],
    post: { label: "인지 태스크 지도", href: "/posts/av-perception-tasks" },
    match: ["TLD"],
  },
  {
    id: "tsr",
    term: "TSR",
    full: "Traffic Sign Recognition",
    category: "인지 태스크",
    summary: "교통 표지판을 검출하고 종류·숫자(속도 제한 등)를 읽는 태스크.",
    body: [
      "TLD와 형제지만 성격이 다르다. 표지판은 **정적**이라 HD 맵에 미리 넣어둘 수 있고, 대신 **종류가 수백 가지**이며 국가마다 다르다.",
      "가변 표지판(전광판 속도 제한), 부속 표지(요일·시간대 조건), 부분 가림, 낡은 표지가 실무 난제다.",
    ],
    related: ["tld", "hd-map", "lmgi"],
    match: ["TSR"],
  },
  {
    id: "lmgi",
    term: "LMGI",
    full: "차선 인식 (조직 내부 약어)",
    category: "인지 태스크",
    summary:
      "차선 인식 태스크를 가리키는 내부 약어. 노면의 차선을 찾아 기하·종류·색을 붙이고, 차선끼리 어떻게 이어지는지(위상)까지 뽑는다.",
    body: [
      "**표기 주의** — LMGI 는 공개 문헌에 정착된 표준 약어가 아니라 조직마다 쓰는 내부 명칭이다. 확장형과 정확한 범위는 사내 스펙 문서가 정의한다. 아래는 공통분모인 **차선 인식**을 기준으로 한 설명이다.",
      "하는 일은 일반적인 차선 검출(LD)과 같다. 이미지 또는 BEV 에서 차선을 찾아 벡터로 뽑고 속성을 붙인다.",
      "- **기하** — 차선을 폴리라인이나 곡선 파라미터로. 픽셀 마스크가 아니라 **선**이어야 계획이 쓸 수 있다.",
      "- **종류** — 실선·점선·이중선",
      "- **색** — 흰색·노란색·파란색(버스전용)",
      "- **위상** — 이 차선이 어느 차선으로 이어지는가. 교차로 안에는 그려진 선이 없어도 논리적 경로는 있다.",
      "조직에 따라 **노면 표시**(진행 방향 화살표, 정지선, 횡단보도, 유도선)까지 같은 태스크군에 넣기도 한다. 같은 카메라의 같은 노면 픽셀에서 나오고 라벨링 도구와 평가 방식이 겹치기 때문이다. 이 범위 차이가 곧 라벨 스펙 차이라서, **어디까지가 LMGI 인지는 사내 온톨로지에서 확인해야 한다.**",
      "왜 중요한가 — 차선은 **계획의 좌표계**다. 물체를 피하는 것만으로는 운전이 안 된다. 빈 공간이라고 다 갈 수 있는 게 아니고(반대 차선도 비어 있다), \"어느 차선으로 어떻게 이어지는가\"가 있어야 갈 수 있는 경로가 한정된다.",
      "실무 난제: 지워지고 겹쳐 칠해진 도색, 눈·물기·역광, 그리고 **끊긴 차선을 어디까지 이어 라벨링할 것인가**라는 스펙 문제. 최근에는 개별 마킹 인지에서 **온라인 맵**(주행 중 차선 위상까지 벡터로 뽑기)으로 무게가 옮겨가고 있다.",
    ],
    related: ["lane-detection", "hd-map", "annotation", "bev", "ontology"],
    post: { label: "차선 검출과 온라인 맵", href: "/posts/av-lane-detection" },
    match: ["LMGI"],
  },
  {
    id: "lane-detection",
    term: "차선 검출",
    full: "Lane Detection (LD)",
    category: "인지 태스크",
    summary: "이미지·BEV에서 차선을 찾아 곡선(폴리라인)으로, 나아가 차선끼리의 연결까지 뽑아내는 태스크.",
    body: [
      "픽셀 분할에서 시작해 **인스턴스 차선 → 곡선 파라미터 → 위상까지 있는 벡터 맵**으로 발전해왔다.",
      "왜 위상이 필요한가 — 계획은 \"흰 선이 여기 있다\"가 아니라 \"이 차선이 저 차선으로 이어진다\"를 요구한다. 교차로 안에는 그려진 선이 없지만 논리적 경로는 있다.",
      "그래서 최근 흐름은 **온라인 맵**이다 — HD 맵을 미리 만들어 두는 대신, 주행 중 카메라로 차선 위상을 즉석에서 그린다(MapTR 계열).",
    ],
    related: ["lmgi", "hd-map", "bev", "planning"],
    post: { label: "차선 검출과 온라인 맵", href: "/posts/av-lane-detection" },
    match: ["차선 검출"],
  },
  {
    id: "freespace",
    term: "주행 가능 영역",
    full: "free space / drivable area",
    category: "인지 태스크",
    summary: "차가 물리적으로 지나갈 수 있는 빈 공간. 박스의 반대편에서 같은 문제를 푼다.",
    body: [
      "\"무엇이 있는가\"가 아니라 **\"어디가 비었는가\"** 를 직접 예측한다. 미지의 장애물에 강하다는 점에서 점유(OCC)와 같은 계보이고, 실제로 점유 격자의 2D 요약으로 쓰이기도 한다.",
      "중요한 구분: **비어 있음(free)** 과 **관측되지 않음(unknown)** 은 다르다. 코너에 가려 안 보이는 영역을 비었다고 표시하면 계획이 그리로 들어간다.",
    ],
    related: ["occ", "segmentation", "planning"],
    match: ["주행 가능 영역", "free space"],
  },
  {
    id: "bev",
    term: "BEV",
    full: "Bird's-Eye View",
    category: "인지 태스크",
    summary: "세상을 위에서 내려다본 2D 격자로 표현하는 방식. 최근 자율주행 인지가 사실상 수렴한 공통 무대.",
    body: [
      "- **거리·크기가 왜곡 없이 보존된다.** 카메라 원근처럼 멀다고 작아지지 않는다.",
      "- **여러 센서를 한 판에 얹기 쉽다.** 라이다도 카메라 6~12대도 같은 격자로 모인다.",
      "- **다운스트림이 통일된다.** 검출·점유·차선·궤적이 전부 같은 BEV 위에서 돈다.",
      "그래서 인지 스택이 \"센서 입력 → **BEV 특징 맵** → 태스크별 헤드\" 모양으로 정렬됐다. 이 구조가 곧 여러 태스크가 하나의 백본을 공유하는 근거다.",
    ],
    related: ["occ", "3dod", "lmgi", "sensor-fusion", "voxel"],
    post: { label: "3D 데이터 표현", href: "/posts/av-3d-data" },
    match: ["BEV"],
  },
  {
    id: "voxel",
    term: "복셀",
    full: "voxel",
    category: "인지 태스크",
    summary: "3D 공간을 규칙적인 정육면체 칸으로 나눈 단위. 픽셀의 3차원 판.",
    body: [
      "정렬되지 않은 점군을 격자에 담아 3D 합성곱을 쓸 수 있게 만든다. 대부분의 칸이 비어 있어 **희소 합성곱(sparse convolution)** 으로 계산을 아낀다.",
      "높이 축을 하나로 눌러 기둥(pillar)으로 만들면 2D 합성곱만으로 처리할 수 있어 훨씬 빠르다(PointPillars). 점유 예측의 출력 격자도 복셀이다.",
    ],
    related: ["point-cloud", "occ", "bev"],
    post: { label: "3D 데이터 표현", href: "/posts/av-3d-data" },
    match: ["복셀"],
  },
  {
    id: "sensor-fusion",
    term: "센서 융합",
    full: "sensor fusion",
    category: "인지 태스크",
    summary: "라이다·카메라·레이더의 정보를 합쳐 각자의 약점을 메우는 일. 합치는 '단계'가 설계의 핵심이다.",
    body: [
      "어느 층에서 합치느냐로 세 갈래가 된다.",
      "- **초기 융합(early)** — 원본 수준에서 합친다. 라이다 점에 그 점이 찍히는 픽셀의 색을 붙이는 식. 정보 손실이 가장 적지만 **캘리브레이션과 시간 동기화 오차에 가장 취약**하다.",
      "- **중간 융합(mid / feature)** — 각 센서를 특징으로 뽑아 BEV 같은 공통 공간에서 합친다. **지금의 주류.** 정보량과 강건함의 균형이 좋다.",
      "- **후기 융합(late)** — 각 센서가 독립적으로 검출한 뒤 결과(트랙)를 합친다. 모듈이 독립적이라 디버깅과 안전 논증이 쉽고, 한 센서가 죽어도 나머지가 돈다. 대신 각 센서가 혼자서는 못 본 약한 신호를 살릴 수 없다.",
      "실무는 섞어 쓴다. 성능을 위해 중간 융합을 하되, **안전을 위해 후기 융합 경로를 하나 더 둔다.**",
      "데이터 쪽 전제는 늘 같다 — **시간 동기화와 좌표 정합.** 융합의 성능 상한은 모델이 아니라 이 둘이 정한다.",
    ],
    related: ["time-sync", "calibration", "bev", "3dod", "tracking"],
    post: { label: "MCAP 완전 정복", href: "/posts/av-mcap" },
    match: ["센서 융합", "sensor fusion"],
  },
  {
    id: "tracking",
    term: "다중 객체 추적",
    full: "MOT, Multi-Object Tracking",
    category: "인지 태스크",
    summary: "프레임마다 나온 검출을 시간축으로 이어 같은 객체에 일관된 id를 붙이는 일.",
    body: [
      "검출은 프레임 단위의 스냅샷이라 그것만으로는 속도도, \"방금 그 차\"도 알 수 없다. 추적이 이를 잇는다.",
      "고전적 구성은 **예측(칼만 필터) → 연관(헝가리안/IoU/외형 유사도) → 갱신**이다. 최근에는 학습 기반 연관이 붙는다.",
      "평가에서 중요한 건 위치 정확도만이 아니라 **id 유지**다. 가려졌다 나타났을 때 id가 바뀌면(id switch) 궤적 예측과 계획이 흔들린다.",
    ],
    related: ["3dod", "track-id", "trajectory", "sensor-fusion"],
    match: ["다중 객체 추적", "MOT"],
  },
  {
    id: "hd-map",
    term: "HD 맵",
    full: "High-Definition Map",
    category: "인지 태스크",
    summary: "차선·정지선·신호등·표지판의 위치와 연결 관계를 cm 급으로 담은 사전 지도.",
    body: [
      "인지의 부담을 크게 덜어준다 — 신호등이 어디 있는지 알고 보면 찾기가 훨씬 쉽고, 차선 위상을 미리 알면 계획이 단순해진다. 측위(localization)의 기준이기도 하다.",
      "대가는 유지비다. 공사·재도색·신설 도로마다 갱신해야 하고, 지도가 현실과 어긋나면 **틀린 확신**을 준다는 점이 더 위험하다.",
      "그래서 흐름은 **의존도를 낮추는 쪽**이다 — 지도는 사전 정보(prior)로만 쓰고 실시간 온라인 맵으로 보완한다.",
    ],
    related: ["lane-detection", "lmgi", "tld", "planning"],
    post: { label: "차선 검출과 온라인 맵", href: "/posts/av-lane-detection" },
    match: ["HD 맵", "HD map"],
  },
  {
    id: "map-metric",
    term: "mAP / NDS",
    full: "mean Average Precision / nuScenes Detection Score",
    category: "인지 태스크",
    summary: "검출 성능을 하나의 숫자로 요약하는 지표. 무엇을 재는지 알고 봐야 한다.",
    body: [
      "**mAP** 는 클래스별 정밀도-재현율 곡선 아래 면적의 평균이다. \"맞다\"의 기준은 IoU 임계값(3D에서는 중심 거리 임계값을 쓰기도 한다)으로 정한다.",
      "**NDS** 는 nuScenes가 쓰는 복합 점수로, mAP에 위치·크기·방향·속도·속성 오차를 함께 넣는다. 박스를 찾았는지뿐 아니라 **얼마나 정확히 찾았는지**를 반영한다.",
      "주의할 것: 전체 mAP 하나로는 안전을 말할 수 없다. **가까운 거리·작은 객체·야간·가려진 객체**로 쪼개서 봐야 실제 위험이 드러난다. 평균은 롱테일을 감춘다.",
    ],
    related: ["3dod", "label-quality", "long-tail"],
    match: ["mAP", "NDS"],
  },

  /* ─────────────────── 예측·계획·제어 ─────────────────── */
  {
    id: "prediction",
    term: "궤적 예측",
    full: "trajectory prediction",
    category: "예측·계획·제어",
    summary: "주변 주체들이 다음 몇 초 동안 어디로 갈지 예측하는 일. 본질적으로 여러 갈래다.",
    body: [
      "핵심 성질 둘.",
      "- **멀티모달** — 앞차가 좌회전할지 직진할지는 하나로 못 정한다. 여러 후보 궤적과 각각의 확률을 낸다. 평균을 내면 아무도 가지 않는 가운데 길이 나온다.",
      "- **상호작용** — 주체들은 서로 영향을 준다. 내가 양보하면 상대가 들어온다. 그래서 **내 계획과 남의 예측이 서로를 참조**한다.",
      "지도가 필수 입력이다. 차선 위상이 있어야 갈 수 있는 경로가 한정된다.",
    ],
    related: ["trajectory", "planning", "tracking", "hd-map"],
    post: { label: "궤적 예측", href: "/posts/av-trajectory" },
    match: ["궤적 예측"],
  },
  {
    id: "trajectory",
    term: "궤적",
    full: "trajectory",
    category: "예측·계획·제어",
    summary: "시간에 따른 위치의 나열. 예측의 출력이자 계획의 출력.",
    body: [
      "경로(path)와 구분한다 — 경로는 \"어디를 지나는가\"이고 궤적은 **\"언제 어디에 있는가\"** 다. 속도가 들어 있어야 충돌 여부를 판단할 수 있다.",
      "로그 스키마에서는 보통 (시각 오프셋, x, y, yaw, 속도) 점들의 나열 + 확률로 적는다. 예측은 후보가 여럿이므로 궤적 집합이 된다.",
    ],
    related: ["prediction", "planning", "control"],
    match: ["궤적"],
  },
  {
    id: "planning",
    term: "계획",
    full: "planning",
    category: "예측·계획·제어",
    summary: "인지·예측 결과를 받아 '앞으로 몇 초간 어떻게 움직일지'를 결정하는 단계.",
    body: [
      "보통 층으로 나뉜다.",
      "- **경로 계획(route)** — 어느 길로 갈 것인가. 내비게이션 수준.",
      "- **행동 계획(behavior)** — 차선을 바꿀까, 양보할까, 추월할까 같은 이산적 결정.",
      "- **동작 계획(motion)** — 그 결정을 실제 궤적으로. 안전·편안함·법규 제약을 만족시키며 최적화한다.",
      "데이터 쪽에서 중요한 건 **왜 그 결정을 했는지 로그에 남기는 것**이다. 선택된 궤적만 남기면 사후 분석에서 \"왜 안 피했나\"에 답할 수 없다. 후보 궤적과 각각이 탈락한 이유(비용 항목별 점수)를 함께 남기는 스택이 디버깅이 압도적으로 쉽다.",
    ],
    related: ["prediction", "control", "trajectory", "freespace", "odd"],
    post: { label: "MCAP 완전 정복", href: "/posts/av-mcap" },
    match: ["행동 계획", "동작 계획", "계획(planning)"],
  },
  {
    id: "control",
    term: "제어",
    full: "control",
    category: "예측·계획·제어",
    summary: "계획된 궤적을 실제 조향·가속·제동 명령으로 바꾸는 단계. 차량 물리와 직접 맞닿는다.",
    body: [
      "대표적 수법은 횡방향의 **Pure Pursuit / Stanley**, 그리고 종횡을 함께 최적화하는 **MPC(모델 예측 제어)** 다. MPC는 차량 모델로 미래를 짧게 시뮬레이션해 제약을 만족하는 명령을 고른다.",
      "로그 관점에서 제어 구간은 **명령과 실제(feedback)를 반드시 쌍으로 남겨야** 한다. `/control/command` 의 목표 조향각과 CAN에서 돌아온 실제 조향각을 나란히 보면, 문제가 계획에 있는지 차량 응답에 있는지 즉시 갈린다.",
      "지연도 여기서 드러난다. 인지 시각 → 제어 명령 시각의 차이가 곧 시스템 반응 지연이고, 이건 로그의 타임스탬프로만 잴 수 있다.",
    ],
    related: ["planning", "can", "trajectory", "log-time"],
    post: { label: "MCAP 완전 정복", href: "/posts/av-mcap" },
    match: ["MPC"],
  },

  /* ─────────────────────────── 모델·학습 ─────────────────────────── */
  {
    id: "vla",
    term: "VLA",
    full: "Vision-Language-Action model",
    category: "모델·학습",
    summary: "시각 입력과 언어를 함께 이해해 **행동**까지 직접 내놓는 모델. 인지→계획→제어의 분리를 하나로 합치려는 시도.",
    body: [
      "로보틱스에서 먼저 나왔고(RT-2, OpenVLA 계열), 자율주행으로 옮겨왔다. 기존 스택이 \"박스 → 궤적 → 조향각\"으로 단계를 밟는다면, VLA는 **센서와 지시를 받아 곧장 행동(궤적 또는 제어량)** 을 낸다.",
      "매력은 둘이다. 중간 표현에서 잃는 정보가 없고, **언어로 근거를 설명**할 수 있다 — \"우측 차량이 끼어들 것 같아 감속했다\".",
      "데이터 관점에서 요구하는 게 완전히 다르다. 필요한 건 박스 라벨이 아니라 **(센서 관측, 상황 설명, 실제 행동) 삼중항**이다.",
      "- **행동**은 CAN에 이미 있다 — 사람이 실제로 어떻게 조향·가감속했는가.",
      "- **관측**은 센서 로그 그대로.",
      "- **언어**가 없다. 그래서 VLM으로 장면을 자동 캡셔닝하거나, 개입·급제동 같은 이벤트에 설명을 붙여 만든다.",
      "즉 VLA는 **모델 문제이기 전에 로그 설계 문제**다. 센서와 행동이 같은 시간축에 정합돼 있지 않으면 학습 데이터 자체를 만들 수 없다. MCAP처럼 모든 단계가 한 파일에 들어가는 포맷이 여기서 값어치를 한다.",
      "주의: 아직 검증·안전 논증이 어렵다는 근본 과제가 남아 있다. \"왜 그렇게 했는가\"를 모듈별로 따질 수 없기 때문이다.",
    ],
    related: ["vqa", "vlm", "e2e", "can", "mcap"],
    post: { label: "VLA·VQA와 파운데이션 모델", href: "/posts/av-foundation-models" },
    match: ["VLA"],
  },
  {
    id: "vqa",
    term: "VQA",
    full: "Visual Question Answering",
    category: "모델·학습",
    summary: "이미지나 장면에 대한 자연어 질문에 답하는 태스크. 자율주행에서는 주로 **데이터 큐레이션과 평가**에 쓰인다.",
    body: [
      "\"이 장면에 우산 쓴 보행자가 있는가?\", \"앞차가 왜 멈췄는가?\" 같은 질문에 답하게 하는 것이다. AV에서 실제로 값어치가 나오는 자리는 셋이다.",
      "- **씬 마이닝·태깅** — 페타바이트 로그에 사람이 태그를 달 수는 없다. VLM/VQA로 날씨·조도·상황을 자동 판정해 컬럼으로 굽는다. **\"비 오는 밤 좌회전 중 보행자\"가 SQL이 되는 실질적 경로가 이것이다.**",
      "- **평가·해석 벤치마크** — DriveLM, NuScenes-QA 같은 데이터셋이 인지·예측·계획을 질문 형태로 묻는다. 모델이 상황을 이해했는지를 박스 정확도가 아닌 방식으로 잰다.",
      "- **오토라벨링 보조** — 애매한 케이스를 사람에게 보내기 전에 1차 분류.",
      "한계도 분명하다. 환각(있지도 않은 걸 있다고 답함)과 공간·거리 감각 부족이 남아 있어, **안전 판단의 근거로는 아직 못 쓴다.** 큐레이션 도구로 쓸 때도 정밀도/재현율을 골든셋으로 재고 임계를 잡아야 한다.",
    ],
    related: ["vlm", "vla", "curation", "annotation"],
    post: { label: "VLA·VQA와 파운데이션 모델", href: "/posts/av-foundation-models" },
    match: ["VQA"],
  },
  {
    id: "vlm",
    term: "VLM",
    full: "Vision-Language Model",
    category: "모델·학습",
    summary: "이미지와 텍스트를 같은 공간에서 다루는 모델. VQA·캡셔닝·이미지 검색의 바탕.",
    body: [
      "CLIP류의 임베딩 모델과, 이미지를 입력받는 대규모 언어모델이 모두 여기 속한다.",
      "AV 데이터 파이프라인에서 가장 실용적인 쓰임은 **임베딩 검색**이다. 로그의 모든 키프레임을 임베딩해 두면 \"이 실패 장면과 비슷한 장면\"을 벡터 검색으로 찾을 수 있다. 롱테일 발굴의 표준 도구가 되고 있다.",
    ],
    related: ["vqa", "vla", "curation", "long-tail"],
    match: ["VLM"],
  },
  {
    id: "e2e",
    term: "E2E 자율주행",
    full: "End-to-End autonomous driving",
    category: "모델·학습",
    summary: "센서 입력에서 주행 행동까지를 하나의 학습된 모델로 잇는 접근.",
    body: [
      "전통적 모듈형 스택(인지 → 예측 → 계획 → 제어)은 각 단계를 따로 검증할 수 있지만, 단계마다 정보를 잃고 오차가 누적된다.",
      "E2E는 그 경계를 없앤다. 최근 흐름은 완전한 블랙박스가 아니라 **인지·예측·계획을 하나의 네트워크에 두되 중간 출력을 남기는** 절충이다(UniAD 계열). 검증 가능성과 성능을 함께 노린다.",
      "데이터 요구가 폭발적으로 커진다는 게 핵심 제약이다. 그리고 **닫힌 루프 평가**가 필수다 — 자기 행동이 다음 관측을 바꾸므로, 로그를 그냥 재생하는 열린 루프 평가로는 성능을 알 수 없다.",
    ],
    related: ["vla", "simulation", "planning"],
    post: { label: "VLA·VQA와 파운데이션 모델", href: "/posts/av-foundation-models" },
    match: ["E2E", "엔드투엔드"],
  },
  {
    id: "simulation",
    term: "시뮬레이션 / 리시뮬",
    full: "simulation, log re-simulation",
    category: "모델·학습",
    summary: "실주행 로그나 합성 환경에서 스택을 다시 돌려 검증하는 일. 실차를 대체하는 게 아니라 증폭한다.",
    body: [
      "- **열린 루프(open-loop)** — 기록된 센서를 그대로 흘려보내고 출력만 비교한다. 인지 회귀 테스트에 쓴다. 싸지만 \"내가 다르게 행동했다면\"을 못 본다.",
      "- **닫힌 루프(closed-loop)** — 내 행동이 세상을 바꾼다. 계획·제어 검증에는 이것만이 유효하다. 대신 상대 차의 반응을 모델링해야 한다.",
      "- **로그 리시뮬** — 실제 로그를 바탕으로 일부만 바꿔 다시 돌린다. 현실성이 높다.",
      "리플레이의 전제가 **결정적 재현성**이다. 같은 로그에 같은 코드를 넣으면 같은 결과가 나와야 한다. 여기서 타임스탬프 규약과 인덱스 정확도가 결정적이다 — MCAP 전환이 검증 인프라에 직접 영향을 주는 지점.",
    ],
    related: ["mcap", "log-time", "e2e", "odd"],
    post: { label: "시뮬레이션과 리시뮬", href: "/posts/av-simulation" },
    match: ["리시뮬", "닫힌 루프", "열린 루프"],
  },
];

/* ─────────────────────────── 조회 헬퍼 ─────────────────────────── */

export const GLOSSARY_BY_ID: Record<string, GlossaryEntry> = Object.fromEntries(
  GLOSSARY.map((e) => [e.id, e])
);

export function getEntry(id: string): GlossaryEntry | undefined {
  return GLOSSARY_BY_ID[id];
}

/**
 * 자동 매칭용 (표기 → id) 목록. 긴 표기를 먼저 시도해야
 * "3D 객체 검출" 이 "검출" 보다 우선한다.
 */
export function matchPatterns(): { pattern: string; id: string }[] {
  const out: { pattern: string; id: string }[] = [];
  for (const e of GLOSSARY) {
    if (e.manualOnly) continue;
    for (const p of e.match ?? [e.term]) out.push({ pattern: p, id: e.id });
  }
  return out.sort((a, b) => b.pattern.length - a.pattern.length);
}
